<?php
$money=static fn(mixed $minor):string=>number_format(((int)$minor)/100,2,',',' ').' PLN';
$type=(string)$campaign['type'];
$effectLabel=match($type){'ad_click'=>t('admin.campaign_report.potwierdzonych_przejsc'),'ad_view'=>t('admin.campaign_report.ukonczonych_obejrzen'),'sponsored_article'=>t('admin.campaign_report.potwierdzonych_przeczytan'),default=>t('admin.campaign_report.ukonczonych_ankiet')};
$eventLabel=static fn(string $event):string=>match($event){'click'=>t('admin.campaign_report.przejscie_z_banera'),'view'=>t('admin.campaign_report.video_view'),'sponsored_read'=>t('bonus.type.article_read'),'survey_completed'=>t('admin.campaign_report.ukonczenie_ankiety'),default=>t('admin.campaign_report.dziaanie_uzytkownika')};
?>
<section class="admin-page-head zs-campaign-report-head"><p class="kicker"><?= e(t('admin.campaign_report.raport_dla_reklamodawcy')) ?></p><h1><?= e((string)$campaign['name']) ?></h1><p><?= e(t('admin.campaign_report.pokazujemy_rezultat_wykorzystany_budzet_i_pozostaa_kwot_15e600a1')) ?></p><div class="zs-campaign-trust-row"><span><?= e((string)($campaign['client_name']??t('admin.campaign_report.client'))) ?></span><span><?= e((string)($campaign['order_reference']??t('admin.campaign_report.no_order_number'))) ?></span><span><?= e(!empty($campaign['budget_confirmed'])?t('admin.campaign_report.budzet_potwierdzony'):t('admin.campaign_report.budzet_czeka_na_potwierdzenie')) ?></span></div></section>

<section class="zs-operator-overview" aria-label="<?= e(t('admin.campaign_report.wynik_kampanii')) ?>">
  <article class="is-ready"><span><?= e(t('admin.campaign_report.potwierdzony_wynik')) ?></span><strong><?= (int)$summary['verified'] ?></strong><small><?= e($effectLabel) ?></small></article>
  <article><span><?= e(t('admin.campaign_report.wykorzystany_budzet')) ?></span><strong><?= $money($summary['spent_minor']) ?></strong><small><?= e(str_replace('{amount}', $money($summary['remaining_minor']), t('admin.campaign_report.remaining_amount'))) ?></small></article>
  <article><span><?= e(t('admin.campaign_report.przyznane_uzytkownikom')) ?></span><strong><?= (int)$summary['rewarded_points'] ?> TT</strong><small><?= e(t('admin.campaign_report.tt_sa_oddzielone_od_budzetu_pln')) ?></small></article>
  <article><span><?= e(t('admin.campaign_report.unikalni_uczestnicy')) ?></span><strong><?= (int)$summary['unique_users'] ?></strong><small><?= e(t('admin.campaign_report.tylko_potwierdzone_wyniki')) ?></small></article>
</section>

<section class="admin-panel-block"><div class="admin-section-head"><div><p class="kicker"><?= e(t('admin.campaign_report.skutecznosc')) ?></p><h2><?= e(t('admin.campaign_report.co_wydarzyo_sie_w_kampanii')) ?></h2></div><span><?= e(t('admin.campaign_report.stan_na_teraz')) ?></span></div>
  <div class="zs-campaign-business-metrics">
    <?php if($type==='ad_click'):?><article><span><?= e(t('admin.campaign_report.wyswietlenia_banera')) ?></span><strong><?= (int)$summary['impressions'] ?></strong></article><article><span><?= e(t('admin.campaign_report.potwierdzone_przejscia')) ?></span><strong><?= (int)$summary['verified'] ?></strong></article><article><span><?= e(t('admin.campaign_report.skutecznosc_klikniec')) ?></span><strong><?= number_format((float)$summary['ctr_percent'],2,',',' ') ?>%</strong></article><?php endif;?>
    <?php if($type==='ad_view'):?><article><span><?= e(t('admin.campaign_report.wyswietlenia')) ?></span><strong><?= (int)$summary['impressions'] ?></strong></article><article><span><?= e(t('admin.campaign_report.rozpoczete_filmy')) ?></span><strong><?= (int)$summary['starts'] ?></strong></article><article><span><?= e(t('admin.campaign_report.ukonczone_obejrzenia')) ?></span><strong><?= (int)$summary['verified'] ?></strong></article><article><span><?= e(t('admin.campaign_report.sredni_czas')) ?></span><strong><?= (int)$summary['average_watch_seconds'] ?> s</strong></article><?php endif;?>
    <?php if($type==='sponsored_article'):?><article><span><?= e(t('admin.campaign_report.wejscia_do_artykuu')) ?></span><strong><?= (int)$summary['starts'] ?></strong></article><article><span><?= e(t('admin.campaign_report.potwierdzone_przeczytania')) ?></span><strong><?= (int)$summary['verified'] ?></strong></article><article><span><?= e(t('admin.campaign_report.ukonczenie')) ?></span><strong><?= number_format((float)$summary['completion_percent'],2,',',' ') ?>%</strong></article><article><span><?= e(t('admin.campaign_report.stawka_za_przeczytanie')) ?></span><strong><?= $money($campaign['event_cost_minor']) ?></strong></article><?php endif;?>
    <?php if($type==='survey_ad'):?><article><span><?= e(t('admin.campaign_report.rozpoczete_ankiety')) ?></span><strong><?= (int)$summary['starts'] ?></strong></article><article><span><?= e(t('admin.campaign_report.ukonczone_ankiety')) ?></span><strong><?= (int)$summary['verified'] ?></strong></article><article><span><?= e(t('admin.campaign_report.ukonczenie')) ?></span><strong><?= number_format((float)$summary['completion_percent'],2,',',' ') ?>%</strong></article><article><span><?= e(t('admin.campaign_report.stawka_za_ukonczenie')) ?></span><strong><?= $money($campaign['event_cost_minor']) ?></strong></article><?php endif;?>
  </div>
  <div class="zs-human-note"><strong><?= e(str_replace('{amount}', $money($summary['estimated_margin_minor']), t('admin.campaign_report.estimated_service_result'))) ?></strong><p><?= e(t('admin.campaign_report.to_wpyw_kampanii_pomniejszony_o_wartosc_przyznanych_tt_6dde8517')) ?></p></div>
</section>

<section class="admin-panel-block"><div class="admin-section-head"><div><p class="kicker"><?= e(t('admin.campaign_report.ostatnie_wyniki')) ?></p><h2><?= e(t('admin.campaign_report.rozliczone_dziaania')) ?></h2></div><span><?= e(str_replace('{count}', (string)count($recent), t('admin.common.items_count'))) ?></span></div>
<?php if($recent===[]):?><div class="empty-state"><h3><?= e(t('admin.campaign_report.jeszcze_bez_wynikow')) ?></h3><p><?= e(t('admin.campaign_report.raport_uzupeni_sie_po_pierwszym_potwierdzonym_dziaaniu_000c15e9')) ?></p></div><?php else:?><div class="admin-table-wrap"><table class="zs-admin-table"><thead><tr><th><?= e(t('wallet.history.table.date')) ?></th><th><?= e(t('admin.campaign_report.dziaanie')) ?></th><th><?= e(t('wallet.orders.table.user')) ?></th><th><?= e(t('admin.campaign_report.wynik')) ?></th><th><?= e(t('admin.campaign_report.rozliczenie')) ?></th></tr></thead><tbody><?php foreach($recent as $event):?><tr><td><?= e((string)$event['created_at']) ?></td><td><strong><?= e($eventLabel((string)$event['event_type'])) ?></strong><?php if((int)$event['watch_seconds']>0):?><small><?= (int)$event['watch_seconds'] ?> s</small><?php endif;?></td><td><?= e((string)($event['user_name']?:$event['email']?:t('wallet.orders.table.user'))) ?></td><td><span class="status-pill <?= $event['verification_status']==='verified'?'is-ready':'is-muted' ?>"><?= e(t($event['verification_status']==='verified' ? 'admin.campaign_report.verified' : 'admin.campaign_report.not_settled')) ?></span></td><td><strong><?= $money($event['cost_minor']) ?></strong><small><?= (int)$event['talent_points_snapshot'] ?> TT</small></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
</section>
<p><a class="btn-line" href="/admin/campaigns?tab=<?= e(match($type){'ad_view'=>'video','sponsored_article'=>'article','survey_ad'=>'survey',default=>'banner'}) ?>&id=<?= (int)$campaign['id'] ?>"><?= e(t('admin.campaign_report.wroc_do_kampanii')) ?></a></p>
