ServerName localhost

<VirtualHost *:8080>
    ServerName localhost
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        AllowOverride All
        Options -Indexes
        Require all granted
        DirectoryIndex index.php
    </Directory>

    RemoteIPHeader X-Forwarded-For
    RemoteIPTrustedProxy 172.16.0.0/12
    RemoteIPTrustedProxy 192.168.0.0/16

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined

    ServerSignature Off
</VirtualHost>
