CREATE TABLE IF NOT EXISTS "security_settings" (
    "id" smallint PRIMARY KEY,
    "dors3_mode" varchar(16) NOT NULL DEFAULT 'prepare',
    "fido2_enabled" smallint NOT NULL DEFAULT 0,
    "fido2_required" smallint NOT NULL DEFAULT 0,
    "critical_step_up_method" varchar(16) NOT NULL DEFAULT 'password',
    "physical_approval" varchar(16) NOT NULL DEFAULT 'disabled',
    "admin_idle_timeout_seconds" integer NOT NULL DEFAULT 900,
    "admin_session_max_seconds" integer NOT NULL DEFAULT 28800,
    "step_up_ttl_seconds" integer NOT NULL DEFAULT 300,
    "challenge_ttl_seconds" integer NOT NULL DEFAULT 300,
    "required_gate" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "updated_by" bigint NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "reason" text NULL,
    CONSTRAINT "security_settings_singleton" CHECK ("id" = 1),
    CONSTRAINT "security_settings_mode" CHECK ("dors3_mode" IN ('prepare', 'test', 'required')),
    CONSTRAINT "security_settings_fido2_enabled" CHECK ("fido2_enabled" IN (0, 1)),
    CONSTRAINT "security_settings_fido2_required" CHECK ("fido2_required" IN (0, 1)),
    CONSTRAINT "security_settings_step_up" CHECK ("critical_step_up_method" IN ('password', 'fido2')),
    CONSTRAINT "security_settings_physical" CHECK ("physical_approval" IN ('disabled', 'enabled')),
    CONSTRAINT "security_settings_idle_range" CHECK ("admin_idle_timeout_seconds" BETWEEN 300 AND 3600),
    CONSTRAINT "security_settings_max_range" CHECK ("admin_session_max_seconds" BETWEEN 3600 AND 86400),
    CONSTRAINT "security_settings_step_up_range" CHECK ("step_up_ttl_seconds" BETWEEN 60 AND 900),
    CONSTRAINT "security_settings_challenge_range" CHECK ("challenge_ttl_seconds" BETWEEN 60 AND 900),
    CONSTRAINT "fk_security_settings_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

INSERT INTO "security_settings" (
    "id", "dors3_mode", "fido2_enabled", "fido2_required",
    "critical_step_up_method", "physical_approval",
    "admin_idle_timeout_seconds", "admin_session_max_seconds",
    "step_up_ttl_seconds", "challenge_ttl_seconds", "reason"
) VALUES (1, 'prepare', 0, 0, 'password', 'disabled', 900, 28800, 300, 300, 'Initial 3DORS prepare mode')
ON CONFLICT ("id") DO NOTHING;

CREATE TABLE IF NOT EXISTS "webauthn_credentials" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL,
    "user_id" bigint NOT NULL,
    "credential_id" text NOT NULL,
    "public_key" text NOT NULL,
    "user_handle" varchar(128) NULL,
    "aaguid" varchar(64) NULL,
    "sign_count" bigint NOT NULL DEFAULT 0,
    "transports" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "display_name" varchar(120) NOT NULL,
    "credential_role" varchar(16) NOT NULL DEFAULT 'primary',
    "status" varchar(16) NOT NULL DEFAULT 'active',
    "tested_at" timestamp without time zone NULL,
    "last_used_at" timestamp without time zone NULL,
    "created_by" bigint NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "revoked_by" bigint NULL,
    "revoked_at" timestamp without time zone NULL,
    "revocation_reason" text NULL,
    CONSTRAINT "uq_webauthn_credentials_public_id" UNIQUE ("public_id"),
    CONSTRAINT "uq_webauthn_credentials_credential_id" UNIQUE ("credential_id"),
    CONSTRAINT "webauthn_credentials_role" CHECK ("credential_role" IN ('primary', 'backup')),
    CONSTRAINT "webauthn_credentials_status" CHECK ("status" IN ('active', 'suspended', 'lost', 'revoked')),
    CONSTRAINT "fk_webauthn_credentials_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_webauthn_credentials_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_webauthn_credentials_revoked_by" FOREIGN KEY ("revoked_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_webauthn_credentials_user_status"
ON "webauthn_credentials" ("user_id", "status");

CREATE TABLE IF NOT EXISTS "webauthn_challenges" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL,
    "user_id" bigint NOT NULL,
    "purpose" varchar(24) NOT NULL,
    "challenge_hash" char(64) NOT NULL,
    "action_fingerprint" char(64) NULL,
    "rp_id" varchar(253) NOT NULL,
    "origin" varchar(512) NOT NULL,
    "request_id" varchar(64) NULL,
    "correlation_id" varchar(64) NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "used_at" timestamp without time zone NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "uq_webauthn_challenges_public_id" UNIQUE ("public_id"),
    CONSTRAINT "uq_webauthn_challenges_hash" UNIQUE ("challenge_hash"),
    CONSTRAINT "webauthn_challenges_purpose" CHECK ("purpose" IN ('registration', 'authentication', 'step_up', 'test')),
    CONSTRAINT "fk_webauthn_challenges_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_webauthn_challenges_expiry"
ON "webauthn_challenges" ("expires_at", "used_at");

CREATE TABLE IF NOT EXISTS "security_recovery_codes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL,
    "user_id" bigint NOT NULL,
    "batch_public_id" varchar(36) NOT NULL,
    "position" smallint NOT NULL,
    "code_hash" varchar(255) NOT NULL,
    "confirmed_at" timestamp without time zone NULL,
    "used_at" timestamp without time zone NULL,
    "used_ip" varchar(64) NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "revoked_at" timestamp without time zone NULL,
    CONSTRAINT "uq_security_recovery_codes_public_id" UNIQUE ("public_id"),
    CONSTRAINT "uq_security_recovery_codes_batch_position" UNIQUE ("user_id", "batch_public_id", "position"),
    CONSTRAINT "security_recovery_codes_position" CHECK ("position" BETWEEN 1 AND 10),
    CONSTRAINT "fk_security_recovery_codes_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_security_recovery_codes_user_active"
ON "security_recovery_codes" ("user_id", "used_at", "revoked_at");

CREATE TABLE IF NOT EXISTS "security_step_up_authorizations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL,
    "user_id" bigint NOT NULL,
    "operation" varchar(120) NOT NULL,
    "action_fingerprint" char(64) NOT NULL,
    "method" varchar(16) NOT NULL,
    "credential_public_id" varchar(36) NULL,
    "context" jsonb NOT NULL,
    "request_id" varchar(64) NULL,
    "correlation_id" varchar(64) NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "consumed_at" timestamp without time zone NULL,
    "invalidated_at" timestamp without time zone NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "uq_security_step_up_public_id" UNIQUE ("public_id"),
    CONSTRAINT "security_step_up_method" CHECK ("method" IN ('password', 'fido2', 'recovery')),
    CONSTRAINT "fk_security_step_up_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_security_step_up_user_expiry"
ON "security_step_up_authorizations" ("user_id", "expires_at", "consumed_at");

CREATE TABLE IF NOT EXISTS "security_events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "event_id" varchar(36) NOT NULL,
    "occurred_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "actor_id" bigint NULL,
    "action" varchar(120) NOT NULL,
    "resource_type" varchar(80) NULL,
    "resource_id" varchar(128) NULL,
    "request_id" varchar(64) NULL,
    "correlation_id" varchar(64) NULL,
    "instance_id" varchar(80) NULL,
    "ip" varchar(64) NULL,
    "user_agent" text NULL,
    "authentication_level" varchar(32) NOT NULL DEFAULT 'unknown',
    "credential_public_id" varchar(36) NULL,
    "before_state" jsonb NULL,
    "after_state" jsonb NULL,
    "result" varchar(24) NOT NULL,
    "reason" text NULL,
    "risk_level" varchar(16) NOT NULL DEFAULT 'low',
    "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT "uq_security_events_event_id" UNIQUE ("event_id"),
    CONSTRAINT "security_events_result" CHECK ("result" IN ('success', 'failure', 'blocked', 'rejected', 'warning')),
    CONSTRAINT "security_events_risk" CHECK ("risk_level" IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT "fk_security_events_actor" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_security_events_actor_time"
ON "security_events" ("actor_id", "occurred_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_security_events_action_time"
ON "security_events" ("action", "occurred_at" DESC);

CREATE TABLE IF NOT EXISTS "security_admin_login_locks" (
    "user_id" bigint PRIMARY KEY,
    "failure_count" integer NOT NULL DEFAULT 0,
    "series_count" integer NOT NULL DEFAULT 0,
    "window_started_at" timestamp without time zone NULL,
    "locked_until" timestamp without time zone NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_admin_login_locks_failure_count" CHECK ("failure_count" >= 0),
    CONSTRAINT "security_admin_login_locks_series_count" CHECK ("series_count" >= 0),
    CONSTRAINT "fk_security_admin_login_locks_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);
