CREATE TABLE IF NOT EXISTS "talent_promotions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(80) NOT NULL,
    "name" varchar(160) NOT NULL,
    "description" text NOT NULL,
    "reward_points" integer NOT NULL DEFAULT 1000,
    "active_invitation_limit" smallint NOT NULL DEFAULT 3,
    "successful_referral_limit" smallint NOT NULL DEFAULT 3,
    "invitation_valid_days" smallint NOT NULL DEFAULT 30,
    "is_promoted" boolean NOT NULL DEFAULT TRUE,
    "starts_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "ends_at" timestamp without time zone DEFAULT NULL,
    "created_by_admin_id" bigint DEFAULT NULL,
    "updated_by_admin_id" bigint DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_talent_promotions_code" UNIQUE ("code"),
    CONSTRAINT "talent_promotions_reward_points" CHECK ("reward_points" BETWEEN 1 AND 1000000),
    CONSTRAINT "talent_promotions_active_limit" CHECK ("active_invitation_limit" BETWEEN 1 AND 100),
    CONSTRAINT "talent_promotions_success_limit" CHECK ("successful_referral_limit" BETWEEN 1 AND 100),
    CONSTRAINT "talent_promotions_valid_days" CHECK ("invitation_valid_days" BETWEEN 1 AND 365),
    CONSTRAINT "talent_promotions_dates" CHECK ("ends_at" IS NULL OR "ends_at" > "starts_at"),
    CONSTRAINT "fk_talent_promotions_created_by" FOREIGN KEY ("created_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_talent_promotions_updated_by" FOREIGN KEY ("updated_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "app_referral_invitations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "public_id" varchar(36) NOT NULL,
    "promotion_id" bigint NOT NULL,
    "inviter_user_id" bigint NOT NULL,
    "invitee_user_id" bigint DEFAULT NULL,
    "invited_email" varchar(190) NOT NULL,
    "reward_points" integer NOT NULL,
    "token_hash" char(64) NOT NULL,
    "device_hash" char(64) DEFAULT NULL,
    "status" varchar(32) NOT NULL DEFAULT 'mail_queued',
    "mail_queue_id" bigint DEFAULT NULL,
    "inviter_reward_job_public_id" varchar(36) DEFAULT NULL,
    "invitee_reward_job_public_id" varchar(36) DEFAULT NULL,
    "created_ip_hash" char(64) DEFAULT NULL,
    "created_user_agent_hash" char(64) DEFAULT NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "mail_sent_at" timestamp without time zone DEFAULT NULL,
    "link_opened_at" timestamp without time zone DEFAULT NULL,
    "installed_at" timestamp without time zone DEFAULT NULL,
    "registered_at" timestamp without time zone DEFAULT NULL,
    "first_session_at" timestamp without time zone DEFAULT NULL,
    "reward_queued_at" timestamp without time zone DEFAULT NULL,
    "rewarded_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_app_referral_invitations_public_id" UNIQUE ("public_id"),
    CONSTRAINT "uq_app_referral_invitations_token" UNIQUE ("token_hash"),
    CONSTRAINT "uq_app_referral_invitations_mail" UNIQUE ("mail_queue_id"),
    CONSTRAINT "app_referral_invitations_reward" CHECK ("reward_points" BETWEEN 1 AND 1000000),
    CONSTRAINT "app_referral_invitations_status" CHECK ("status" IN (
        'mail_queued','sent','link_opened','installed','registered','reward_queued','rewarded',
        'mail_dead_letter','cancelled','expired'
    )),
    CONSTRAINT "app_referral_invitations_distinct_users" CHECK ("invitee_user_id" IS NULL OR "invitee_user_id" <> "inviter_user_id"),
    CONSTRAINT "fk_app_referral_promotion" FOREIGN KEY ("promotion_id") REFERENCES "talent_promotions" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_app_referral_inviter" FOREIGN KEY ("inviter_user_id") REFERENCES "users" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_app_referral_invitee" FOREIGN KEY ("invitee_user_id") REFERENCES "users" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_app_referral_mail" FOREIGN KEY ("mail_queue_id") REFERENCES "mail_queue" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_talent_promotions_public"
ON "talent_promotions" ("is_promoted", "starts_at", "ends_at");

CREATE INDEX IF NOT EXISTS "idx_app_referral_inviter_status"
ON "app_referral_invitations" ("inviter_user_id", "status", "created_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_app_referral_promotion_status"
ON "app_referral_invitations" ("promotion_id", "status", "created_at" DESC);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_app_referral_active_email"
ON "app_referral_invitations" (LOWER("invited_email"))
WHERE "status" IN ('mail_queued','sent','link_opened','installed','registered');

CREATE UNIQUE INDEX IF NOT EXISTS "uq_app_referral_success_email"
ON "app_referral_invitations" (LOWER("invited_email"))
WHERE "status" IN ('reward_queued','rewarded');

CREATE UNIQUE INDEX IF NOT EXISTS "uq_app_referral_device"
ON "app_referral_invitations" ("device_hash")
WHERE "device_hash" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "uq_app_referral_invitee"
ON "app_referral_invitations" ("invitee_user_id")
WHERE "invitee_user_id" IS NOT NULL;

INSERT INTO "talent_promotions" (
    "code","name","description","reward_points","active_invitation_limit",
    "successful_referral_limit","invitation_valid_days","is_promoted","starts_at",
    "created_at","updated_at"
) VALUES (
    'app_referral','Bonus za instalację aplikacji',
    'Obie strony otrzymują punkty Talent po instalacji aplikacji, pierwszej rejestracji i pierwszej prawidłowej sesji.',
    1000,3,3,30,TRUE,NOW(),NOW(),NOW()
) ON CONFLICT ("code") DO NOTHING;

INSERT INTO "activity_reward_rules" (
    "activity_type","points_amount","amount_minor","label","live_message_template",
    "title_key","message_key","description_key","daily_limit","is_active","created_at","updated_at"
) VALUES (
    'app_referral_bonus',0,0,'Bonus za polecenie aplikacji','Bonus za skuteczne polecenie aplikacji',
    'bonus.type.app_referral','bonus.message.app_referral','bonus.description.app_referral',0,1,NOW(),NOW()
) ON CONFLICT ("activity_type") DO UPDATE SET
    "title_key"=EXCLUDED."title_key",
    "message_key"=EXCLUDED."message_key",
    "description_key"=EXCLUDED."description_key",
    "updated_at"=NOW();
