-- ETAP 7: księga per-portfel, kontrolowane przełączenie i okresowe anchory Merkle.

ALTER TABLE "wallet_transactions"
    ADD COLUMN IF NOT EXISTS "wallet_previous_hash" char(64) NULL,
    ADD COLUMN IF NOT EXISTS "wallet_entry_hash" char(64) NULL,
    ADD COLUMN IF NOT EXISTS "wallet_hash_algorithm" varchar(20) NULL,
    ADD COLUMN IF NOT EXISTS "wallet_hash_version" integer NULL,
    ADD COLUMN IF NOT EXISTS "wallet_signed_at" timestamp without time zone NULL;

CREATE INDEX IF NOT EXISTS "idx_wallet_transactions_wallet_chain"
    ON "wallet_transactions" ("wallet_id","id");

CREATE TABLE IF NOT EXISTS "financial_ledger_migration_state" (
    "id" smallint PRIMARY KEY,
    "mode" varchar(24) NOT NULL CHECK ("mode" IN ('legacy_global','per_wallet')),
    "legacy_cutover_transaction_id" bigint NULL,
    "compliance_report_json" jsonb NULL,
    "compliance_report_hash" char(64) NULL,
    "verified_at" timestamp without time zone NULL,
    "activated_at" timestamp without time zone NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "financial_ledger_migration_state" ("id","mode","updated_at")
VALUES (1,'legacy_global',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

CREATE TABLE IF NOT EXISTS "financial_wallet_ledger_heads" (
    "wallet_id" bigint PRIMARY KEY,
    "last_transaction_id" bigint NULL,
    "last_entry_hash" char(64) NOT NULL,
    "transaction_count" bigint NOT NULL DEFAULT 0 CHECK ("transaction_count" >= 0),
    "hash_version" integer NOT NULL DEFAULT 2,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_financial_wallet_ledger_heads_wallet"
        FOREIGN KEY ("wallet_id") REFERENCES "wallets" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_financial_wallet_ledger_heads_transaction"
        FOREIGN KEY ("last_transaction_id") REFERENCES "wallet_transactions" ("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "financial_operations" (
    "idempotency_key" varchar(190) PRIMARY KEY,
    "request_hash" char(64) NOT NULL,
    "status" varchar(16) NOT NULL CHECK ("status" IN ('processing','completed')),
    "wallet_id" bigint NULL,
    "transaction_id" bigint NULL UNIQUE,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" timestamp without time zone NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_financial_operations_wallet"
        FOREIGN KEY ("wallet_id") REFERENCES "wallets" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_financial_operations_transaction"
        FOREIGN KEY ("transaction_id") REFERENCES "wallet_transactions" ("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "financial_ledger_anchors" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "period_start" timestamp without time zone NOT NULL,
    "period_end" timestamp without time zone NOT NULL,
    "cutoff_transaction_id" bigint NULL,
    "wallet_count" integer NOT NULL DEFAULT 0 CHECK ("wallet_count" >= 0),
    "transaction_count" bigint NOT NULL DEFAULT 0 CHECK ("transaction_count" >= 0),
    "merkle_root" char(64) NOT NULL,
    "previous_anchor_hash" char(64) NOT NULL,
    "anchor_hash" char(64) NOT NULL,
    "hash_algorithm" varchar(20) NOT NULL DEFAULT 'hmac-sha256',
    "hash_version" integer NOT NULL DEFAULT 2,
    "manifest_json" jsonb NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uq_financial_ledger_anchors_period" UNIQUE ("period_start","period_end")
);

CREATE INDEX IF NOT EXISTS "idx_financial_ledger_anchors_created"
    ON "financial_ledger_anchors" ("created_at","id");
