-- Kontrolowane, selektywne przywracanie treści i portfela administratora.

CREATE TABLE IF NOT EXISTS "selected_migration_runs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(64) NOT NULL UNIQUE,
    "mode" varchar(16) NOT NULL CHECK ("mode" IN ('dry-run','apply','resume')),
    "source_database" varchar(190) NOT NULL,
    "source_admin_id" bigint NOT NULL,
    "source_manifest_hash" char(64) NOT NULL,
    "financial_approval" varchar(255) NOT NULL,
    "status" varchar(20) NOT NULL CHECK ("status" IN ('running','completed','failed')),
    "report_json" jsonb NULL,
    "started_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" timestamp without time zone NULL
);

CREATE INDEX IF NOT EXISTS "idx_selected_migration_runs_status"
    ON "selected_migration_runs" ("status","started_at");

CREATE TABLE IF NOT EXISTS "selected_migration_legacy_wallet_transactions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "run_id" bigint NOT NULL REFERENCES "selected_migration_runs" ("id") ON DELETE RESTRICT,
    "source_transaction_id" bigint NOT NULL,
    "source_wallet_id" bigint NOT NULL,
    "source_user_id" bigint NOT NULL,
    "original_previous_hash" varchar(128) NULL,
    "original_entry_hash" varchar(128) NULL,
    "original_hash_algorithm" varchar(20) NULL,
    "original_hash_version" integer NULL,
    "source_row_json" jsonb NOT NULL,
    "source_row_checksum" char(64) NOT NULL,
    "archived_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uq_selected_legacy_wallet_transaction" UNIQUE ("run_id","source_transaction_id")
);

CREATE INDEX IF NOT EXISTS "idx_selected_legacy_wallet_transactions_source"
    ON "selected_migration_legacy_wallet_transactions" ("source_user_id","source_wallet_id","source_transaction_id");

CREATE TABLE IF NOT EXISTS "selected_migration_article_authors" (
    "run_id" bigint NOT NULL REFERENCES "selected_migration_runs" ("id") ON DELETE RESTRICT,
    "source_article_id" bigint NOT NULL,
    "original_author_id" bigint NOT NULL,
    "target_admin_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("run_id","source_article_id")
);

CREATE OR REPLACE FUNCTION protect_selected_migration_archive()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'Archiwum selektywnej migracji jest niezmienne.';
END
$function$;

DROP TRIGGER IF EXISTS "trg_protect_selected_migration_legacy_wallet_transactions"
    ON "selected_migration_legacy_wallet_transactions";
CREATE TRIGGER "trg_protect_selected_migration_legacy_wallet_transactions"
BEFORE UPDATE OR DELETE ON "selected_migration_legacy_wallet_transactions"
FOR EACH ROW EXECUTE FUNCTION protect_selected_migration_archive();

DROP TRIGGER IF EXISTS "trg_protect_selected_migration_article_authors"
    ON "selected_migration_article_authors";
CREATE TRIGGER "trg_protect_selected_migration_article_authors"
BEFORE UPDATE OR DELETE ON "selected_migration_article_authors"
FOR EACH ROW EXECUTE FUNCTION protect_selected_migration_archive();
