CREATE TABLE IF NOT EXISTS "security_mobile_devices" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL UNIQUE,
    "user_id" bigint NOT NULL,
    "organization_id" varchar(128) NOT NULL,
    "agreement_id" bigint NULL,
    "application_variant" varchar(16) NOT NULL,
    "display_name" varchar(120) NOT NULL,
    "platform" varchar(24) NOT NULL DEFAULT 'android',
    "app_version" varchar(32) NOT NULL,
    "device_model" varchar(160) NOT NULL,
    "os_version" varchar(80) NOT NULL,
    "security_level" varchar(24) NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'pending',
    "registered_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "activated_at" timestamp without time zone NULL,
    "last_used_at" timestamp without time zone NULL,
    "suspended_at" timestamp without time zone NULL,
    "revoked_at" timestamp without time zone NULL,
    "revoked_by" bigint NULL,
    "revocation_reason" text NULL,
    "created_request_id" varchar(36) NOT NULL,
    CONSTRAINT "security_mobile_devices_variant" CHECK ("application_variant" IN ('admin', 'author')),
    CONSTRAINT "security_mobile_devices_status" CHECK ("status" IN ('pending', 'active', 'suspended', 'lost', 'revoked', 'expired')),
    CONSTRAINT "security_mobile_devices_security" CHECK ("security_level" IN ('STRONGBOX', 'TEE', 'SOFTWARE')),
    CONSTRAINT "fk_security_mobile_devices_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_security_mobile_devices_revoked_by" FOREIGN KEY ("revoked_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_security_mobile_devices_user_variant_status"
ON "security_mobile_devices" ("user_id", "application_variant", "status");

CREATE TABLE IF NOT EXISTS "security_mobile_credentials" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL UNIQUE,
    "device_id" bigint NOT NULL,
    "public_key" text NOT NULL,
    "algorithm" varchar(40) NOT NULL,
    "key_reference" varchar(160) NOT NULL,
    "security_level" varchar(24) NOT NULL,
    "attestation_metadata" jsonb NULL,
    "status" varchar(16) NOT NULL DEFAULT 'pending',
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "last_signature_at" timestamp without time zone NULL,
    "revoked_at" timestamp without time zone NULL,
    "revocation_reason" text NULL,
    CONSTRAINT "security_mobile_credentials_status" CHECK ("status" IN ('pending', 'active', 'suspended', 'revoked')),
    CONSTRAINT "security_mobile_credentials_algorithm" CHECK ("algorithm" = 'SHA256withECDSA'),
    CONSTRAINT "security_mobile_credentials_security" CHECK ("security_level" IN ('STRONGBOX', 'TEE', 'SOFTWARE')),
    CONSTRAINT "fk_security_mobile_credentials_device" FOREIGN KEY ("device_id") REFERENCES "security_mobile_devices" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_security_mobile_credentials_device_status"
ON "security_mobile_credentials" ("device_id", "status");

CREATE TABLE IF NOT EXISTS "security_mobile_enrollments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL UNIQUE,
    "user_id" bigint NOT NULL,
    "organization_id" varchar(128) NOT NULL,
    "agreement_id" bigint NULL,
    "application_variant" varchar(16) NOT NULL,
    "token_hash" char(64) NOT NULL UNIQUE,
    "comparison_code_hash" char(64) NOT NULL,
    "comparison_code_ciphertext" text NOT NULL,
    "browser_session_hash" char(64) NOT NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "used_at" timestamp without time zone NULL,
    "confirmed_at" timestamp without time zone NULL,
    "status" varchar(16) NOT NULL DEFAULT 'pending',
    "created_by" bigint NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_mobile_enrollments_variant" CHECK ("application_variant" IN ('admin', 'author')),
    CONSTRAINT "security_mobile_enrollments_status" CHECK ("status" IN ('pending', 'completed', 'confirmed', 'failed', 'expired')),
    CONSTRAINT "fk_security_mobile_enrollments_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_security_mobile_enrollments_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_security_mobile_enrollments_expiry"
ON "security_mobile_enrollments" ("status", "expires_at");

CREATE TABLE IF NOT EXISTS "security_mobile_approval_requests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL UNIQUE,
    "user_id" bigint NOT NULL,
    "organization_id" varchar(128) NOT NULL,
    "role_context" varchar(64) NOT NULL,
    "device_id" bigint NULL,
    "credential_id" bigint NULL,
    "application_variant" varchar(16) NOT NULL,
    "purpose" varchar(16) NOT NULL,
    "action_type" varchar(120) NOT NULL,
    "resource_type" varchar(80) NULL,
    "resource_id" varchar(128) NULL,
    "action_fingerprint" char(64) NULL,
    "display_payload_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "challenge_hash" char(64) NOT NULL UNIQUE,
    "challenge_ciphertext" text NOT NULL,
    "browser_session_hash" char(64) NOT NULL,
    "server_origin" varchar(512) NOT NULL,
    "environment" varchar(24) NOT NULL,
    "protocol_version" smallint NOT NULL DEFAULT 1,
    "nonce_hash" char(64) NOT NULL UNIQUE,
    "nonce_ciphertext" text NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'pending',
    "issued_at" timestamp without time zone NOT NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "approved_at" timestamp without time zone NULL,
    "rejected_at" timestamp without time zone NULL,
    "consumed_at" timestamp without time zone NULL,
    "request_id" varchar(64) NOT NULL,
    "correlation_id" varchar(128) NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_mobile_approval_variant" CHECK ("application_variant" IN ('admin', 'author')),
    CONSTRAINT "security_mobile_approval_purpose" CHECK ("purpose" IN ('login', 'operation')),
    CONSTRAINT "security_mobile_approval_status" CHECK ("status" IN ('pending', 'approved', 'rejected', 'expired', 'consumed', 'cancelled')),
    CONSTRAINT "security_mobile_approval_protocol" CHECK ("protocol_version" = 1),
    CONSTRAINT "fk_security_mobile_approval_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_security_mobile_approval_device" FOREIGN KEY ("device_id") REFERENCES "security_mobile_devices" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_security_mobile_approval_credential" FOREIGN KEY ("credential_id") REFERENCES "security_mobile_credentials" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_security_mobile_approval_pending_device"
ON "security_mobile_approval_requests" ("device_id", "status", "expires_at");
CREATE INDEX IF NOT EXISTS "idx_security_mobile_approval_user_time"
ON "security_mobile_approval_requests" ("user_id", "created_at" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_security_mobile_requests_pending_operation"
ON "security_mobile_approval_requests" (
    "user_id", "application_variant", "action_type", COALESCE("resource_type", ''), COALESCE("resource_id", '')
)
WHERE "status" = 'pending' AND "purpose" = 'operation';

CREATE TABLE IF NOT EXISTS "security_mobile_signatures" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "approval_request_id" bigint NOT NULL,
    "device_id" bigint NOT NULL,
    "credential_id" bigint NOT NULL,
    "decision" varchar(16) NOT NULL,
    "signature" text NOT NULL,
    "signed_payload_hash" char(64) NOT NULL,
    "algorithm" varchar(40) NOT NULL,
    "verification_result" varchar(16) NOT NULL,
    "failure_reason" text NULL,
    "signed_at" timestamp without time zone NOT NULL,
    "verified_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "request_id" varchar(64) NOT NULL,
    CONSTRAINT "security_mobile_signatures_decision" CHECK ("decision" IN ('approve', 'reject')),
    CONSTRAINT "security_mobile_signatures_verification" CHECK ("verification_result" IN ('valid', 'invalid')),
    CONSTRAINT "fk_security_mobile_signatures_request" FOREIGN KEY ("approval_request_id") REFERENCES "security_mobile_approval_requests" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_security_mobile_signatures_device" FOREIGN KEY ("device_id") REFERENCES "security_mobile_devices" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_security_mobile_signatures_credential" FOREIGN KEY ("credential_id") REFERENCES "security_mobile_credentials" ("id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "idx_security_mobile_signatures_request"
ON "security_mobile_signatures" ("approval_request_id", "verified_at" DESC);

CREATE TABLE IF NOT EXISTS "security_mobile_operation_policies" (
    "action_type" varchar(120) PRIMARY KEY,
    "application_variant" varchar(16) NOT NULL,
    "policy" varchar(32) NOT NULL,
    "enforced" smallint NOT NULL DEFAULT 0,
    "threshold_minor" bigint NULL,
    "updated_by" bigint NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_mobile_policy_variant" CHECK ("application_variant" IN ('admin', 'author')),
    CONSTRAINT "security_mobile_policy_value" CHECK ("policy" IN ('none', 'password_step_up', 'mobile', 'fido2', 'mobile_or_fido2', 'mobile_and_fido2')),
    CONSTRAINT "security_mobile_policy_enforced" CHECK ("enforced" IN (0, 1)),
    CONSTRAINT "fk_security_mobile_policy_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

INSERT INTO "security_mobile_operation_policies" ("action_type", "application_variant", "policy", "enforced") VALUES
('payout.approve', 'admin', 'mobile', 0),
('payout.reject', 'admin', 'mobile', 0),
('wallet.adjust', 'admin', 'mobile', 0),
('payout_details.admin_change', 'admin', 'mobile', 0),
('ledger.manual_correction', 'admin', 'mobile_and_fido2', 0),
('role.change', 'admin', 'mobile', 0),
('security.settings.change', 'admin', 'mobile_and_fido2', 0),
('device.register', 'admin', 'mobile', 0),
('device.revoke', 'admin', 'mobile', 0),
('admin.approve', 'admin', 'mobile', 0),
('dors3.policy.change', 'admin', 'mobile_and_fido2', 0),
('backup.restore', 'admin', 'mobile_and_fido2', 0),
('sensitive_data.export', 'admin', 'mobile_and_fido2', 0),
('financial_settings.change', 'admin', 'mobile_and_fido2', 0),
('safety_fund.disbursement', 'admin', 'mobile_and_fido2', 0),
('article.submit', 'author', 'mobile', 0),
('article.send_to_editor', 'author', 'mobile', 0),
('article.approve_version', 'author', 'mobile', 0),
('article.publish', 'author', 'mobile', 0),
('article.unpublish', 'author', 'mobile', 0),
('article.export_sources', 'author', 'mobile', 0),
('confidential_material.access', 'author', 'mobile', 0),
('payout_details.change', 'author', 'mobile', 0),
('wallet.own_operation', 'author', 'mobile', 0),
('agreement.action', 'author', 'mobile', 0)
ON CONFLICT ("action_type") DO NOTHING;

CREATE TABLE IF NOT EXISTS "security_mobile_deferred_operations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "approval_request_id" bigint NOT NULL UNIQUE,
    "operation_payload_json" jsonb NOT NULL,
    "expected_fingerprint" char(64) NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'pending',
    "executed_at" timestamp without time zone NULL,
    "failure_reason" text NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_mobile_deferred_status" CHECK ("status" IN ('pending', 'executed', 'failed', 'cancelled')),
    CONSTRAINT "fk_security_mobile_deferred_request" FOREIGN KEY ("approval_request_id") REFERENCES "security_mobile_approval_requests" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "security_mobile_rate_limits" (
    "limit_key" char(64) NOT NULL,
    "bucket_started_at" timestamp without time zone NOT NULL,
    "attempt_count" integer NOT NULL DEFAULT 0,
    "expires_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("limit_key", "bucket_started_at"),
    CONSTRAINT "security_mobile_rate_limit_count" CHECK ("attempt_count" >= 0)
);

CREATE INDEX IF NOT EXISTS "idx_security_mobile_rate_limits_expiry"
ON "security_mobile_rate_limits" ("expires_at");
