CREATE TABLE IF NOT EXISTS "author_agreements" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL UNIQUE,
    "user_id" bigint NOT NULL,
    "organization_id" varchar(128) NOT NULL DEFAULT 'zrodlo-slowa',
    "status" varchar(16) NOT NULL DEFAULT 'active',
    "valid_from" timestamp without time zone NOT NULL,
    "valid_until" timestamp without time zone NULL,
    "terms_version" varchar(40) NOT NULL DEFAULT 'legacy-v1',
    "created_by" bigint NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "author_agreements_status" CHECK ("status" IN ('active', 'suspended', 'expired', 'terminated')),
    CONSTRAINT "author_agreements_validity" CHECK ("valid_until" IS NULL OR "valid_until" > "valid_from"),
    CONSTRAINT "fk_author_agreements_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_author_agreements_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_author_agreements_active_user_org"
ON "author_agreements" ("user_id", "organization_id")
WHERE "status" = 'active';

CREATE INDEX IF NOT EXISTS "idx_author_agreements_eligibility"
ON "author_agreements" ("user_id", "organization_id", "status", "valid_from", "valid_until");

-- Zachowuje istniejące uprawnienia autorów jako jawne, audytowalne umowy
-- przejściowe. Od tej migracji sama flaga can_write nie wystarcza.
INSERT INTO "author_agreements" (
    "public_id", "user_id", "organization_id", "status", "valid_from", "terms_version", "created_at", "updated_at"
)
SELECT
    substr(md5('3dors-agreement:' || u.id::text || ':' || clock_timestamp()::text), 1, 8) || '-' ||
    substr(md5('3dors-agreement:' || u.id::text || ':' || clock_timestamp()::text), 9, 4) || '-' ||
    substr(md5('3dors-agreement:' || u.id::text || ':' || clock_timestamp()::text), 13, 4) || '-' ||
    substr(md5('3dors-agreement:' || u.id::text || ':' || clock_timestamp()::text), 17, 4) || '-' ||
    substr(md5('3dors-agreement:' || u.id::text || ':' || clock_timestamp()::text), 21, 12),
    u.id,
    'zrodlo-slowa',
    'active',
    NOW(),
    'legacy-v1',
    NOW(),
    NOW()
FROM "users" u
WHERE u."status" = 'active'
  AND u."can_write" = 1
  AND (u."article_submit_blocked_until" IS NULL OR u."article_submit_blocked_until" <= NOW())
  AND EXISTS (SELECT 1 FROM "user_roles" ur WHERE ur."user_id" = u."id" AND ur."role" = 'author')
  AND NOT EXISTS (
      SELECT 1 FROM "author_agreements" a
      WHERE a."user_id" = u."id" AND a."organization_id" = 'zrodlo-slowa' AND a."status" = 'active'
  );

ALTER TABLE "security_mobile_enrollments"
    DROP CONSTRAINT IF EXISTS "security_mobile_enrollments_status";
ALTER TABLE "security_mobile_enrollments"
    ADD CONSTRAINT "security_mobile_enrollments_status"
    CHECK ("status" IN ('pending', 'completed', 'confirmed', 'failed', 'expired', 'cancelled'));

ALTER TABLE "security_mobile_enrollments"
    DROP CONSTRAINT IF EXISTS "fk_security_mobile_enrollments_agreement";
ALTER TABLE "security_mobile_enrollments"
    ADD CONSTRAINT "fk_security_mobile_enrollments_agreement"
    FOREIGN KEY ("agreement_id") REFERENCES "author_agreements" ("id") ON DELETE RESTRICT;

ALTER TABLE "security_mobile_devices"
    DROP CONSTRAINT IF EXISTS "fk_security_mobile_devices_agreement";
ALTER TABLE "security_mobile_devices"
    ADD CONSTRAINT "fk_security_mobile_devices_agreement"
    FOREIGN KEY ("agreement_id") REFERENCES "author_agreements" ("id") ON DELETE RESTRICT;

ALTER TABLE "security_mobile_credentials"
    ADD COLUMN IF NOT EXISTS "api_token_hash" char(64) NULL,
    ADD COLUMN IF NOT EXISTS "api_token_expires_at" timestamp without time zone NULL,
    ADD COLUMN IF NOT EXISTS "api_token_last_used_at" timestamp without time zone NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "uq_security_mobile_credentials_api_token"
ON "security_mobile_credentials" ("api_token_hash")
WHERE "api_token_hash" IS NOT NULL;

ALTER TABLE "financial_approvals"
    ADD COLUMN IF NOT EXISTS "source" varchar(40) NOT NULL DEFAULT 'web',
    ADD COLUMN IF NOT EXISTS "external_request_id" varchar(36) NULL,
    ADD COLUMN IF NOT EXISTS "correlation_id" varchar(128) NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "uq_financial_approvals_external_request"
ON "financial_approvals" ("source", "external_request_id")
WHERE "external_request_id" IS NOT NULL;

INSERT INTO "security_mobile_operation_policies" ("action_type", "application_variant", "policy", "enforced") VALUES
('article.reject', 'admin', 'mobile', 0)
ON CONFLICT ("action_type") DO NOTHING;
