-- Safety Fund is an internal editorial revenue allocation in the existing ledger.
-- The initial policy replaces the former 70/30 split with 40/40/20.

CREATE TABLE IF NOT EXISTS "revenue_split_policies" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "version" integer NOT NULL,
    "author_basis_points" integer NOT NULL,
    "platform_basis_points" integer NOT NULL,
    "safety_fund_basis_points" integer NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'active',
    "effective_from" timestamp without time zone NOT NULL,
    "created_by" bigint NULL,
    "activated_by" bigint NULL,
    "approval_request_public_id" varchar(36) NULL,
    "created_at" timestamp without time zone NOT NULL,
    "activated_at" timestamp without time zone NULL,
    "retired_at" timestamp without time zone NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_revenue_split_policies_version" UNIQUE ("version"),
    CONSTRAINT "uq_revenue_split_policies_approval_request" UNIQUE ("approval_request_public_id"),
    CONSTRAINT "chk_revenue_split_policy_status" CHECK ("status" IN ('active','retired')),
    CONSTRAINT "chk_revenue_split_policy_author" CHECK ("author_basis_points" BETWEEN 0 AND 10000),
    CONSTRAINT "chk_revenue_split_policy_platform" CHECK ("platform_basis_points" BETWEEN 0 AND 10000),
    CONSTRAINT "chk_revenue_split_policy_safety" CHECK ("safety_fund_basis_points" BETWEEN 0 AND 10000),
    CONSTRAINT "chk_revenue_split_policy_total" CHECK (
        "author_basis_points" + "platform_basis_points" + "safety_fund_basis_points" = 10000
    ),
    CONSTRAINT "fk_revenue_split_policy_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_revenue_split_policy_activated_by" FOREIGN KEY ("activated_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_revenue_split_policies_one_active"
ON "revenue_split_policies" ((1)) WHERE "status" = 'active';

INSERT INTO "revenue_split_policies" (
    "version", "author_basis_points", "platform_basis_points", "safety_fund_basis_points",
    "status", "effective_from", "created_at", "activated_at"
)
SELECT 1, 4000, 4000, 2000, 'active', NOW(), NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM "revenue_split_policies");

-- Article valuation no longer carries an independently editable split. Keep the
-- legacy snapshot columns aligned with the active initial policy for display and
-- compatibility; each purchase below stores its exact versioned policy.
ALTER TABLE "articles"
    ALTER COLUMN "author_share_percent" SET DEFAULT 40.00,
    ALTER COLUMN "platform_share_percent" SET DEFAULT 40.00;

UPDATE "articles"
SET "author_share_percent" = 40.00,
    "platform_share_percent" = 40.00;

ALTER TABLE "article_purchases"
    ADD COLUMN IF NOT EXISTS "split_policy_id" bigint NULL,
    ADD COLUMN IF NOT EXISTS "author_share_basis_points" integer NOT NULL DEFAULT 7000,
    ADD COLUMN IF NOT EXISTS "platform_share_basis_points" integer NOT NULL DEFAULT 3000,
    ADD COLUMN IF NOT EXISTS "safety_fund_share_basis_points" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "safety_fund_amount_minor" bigint NOT NULL DEFAULT 0;

UPDATE "article_purchases"
SET "author_share_basis_points" = ROUND("author_share_percent" * 100)::integer,
    "platform_share_basis_points" = ROUND("platform_share_percent" * 100)::integer,
    "safety_fund_share_basis_points" = 0
WHERE "split_policy_id" IS NULL;

ALTER TABLE "article_purchases"
    ALTER COLUMN "author_share_basis_points" SET DEFAULT 4000,
    ALTER COLUMN "platform_share_basis_points" SET DEFAULT 4000,
    ALTER COLUMN "safety_fund_share_basis_points" SET DEFAULT 2000;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_article_purchases_split_policy') THEN
        ALTER TABLE "article_purchases"
            ADD CONSTRAINT "fk_article_purchases_split_policy"
            FOREIGN KEY ("split_policy_id") REFERENCES "revenue_split_policies" ("id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_article_purchases_split_amounts') THEN
        ALTER TABLE "article_purchases"
            ADD CONSTRAINT "chk_article_purchases_split_amounts"
            CHECK ("total_amount_minor" = "author_amount_minor" + "platform_amount_minor" + "safety_fund_amount_minor");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_article_purchases_split_basis_points') THEN
        ALTER TABLE "article_purchases"
            ADD CONSTRAINT "chk_article_purchases_split_basis_points"
            CHECK ("author_share_basis_points" + "platform_share_basis_points" + "safety_fund_share_basis_points" = 10000);
    END IF;
END
$$;

ALTER TABLE "platform_revenues"
    ADD COLUMN IF NOT EXISTS "split_policy_id" bigint NULL,
    ADD COLUMN IF NOT EXISTS "author_share_basis_points" integer NOT NULL DEFAULT 7000,
    ADD COLUMN IF NOT EXISTS "platform_share_basis_points" integer NOT NULL DEFAULT 3000,
    ADD COLUMN IF NOT EXISTS "safety_fund_share_basis_points" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "safety_fund_amount_minor" bigint NOT NULL DEFAULT 0;

UPDATE "platform_revenues"
SET "platform_share_basis_points" = ROUND("publisher_fee_percent" * 100)::integer,
    "author_share_basis_points" = 10000 - ROUND("publisher_fee_percent" * 100)::integer,
    "safety_fund_share_basis_points" = 0
WHERE "split_policy_id" IS NULL;

ALTER TABLE "platform_revenues"
    ALTER COLUMN "author_share_basis_points" SET DEFAULT 4000,
    ALTER COLUMN "platform_share_basis_points" SET DEFAULT 4000,
    ALTER COLUMN "safety_fund_share_basis_points" SET DEFAULT 2000;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_platform_revenues_split_policy') THEN
        ALTER TABLE "platform_revenues"
            ADD CONSTRAINT "fk_platform_revenues_split_policy"
            FOREIGN KEY ("split_policy_id") REFERENCES "revenue_split_policies" ("id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_platform_revenues_split_amounts') THEN
        ALTER TABLE "platform_revenues"
            ADD CONSTRAINT "chk_platform_revenues_split_amounts"
            CHECK ("total_amount_minor" = "author_income_minor" + "publisher_fee_minor" + "safety_fund_amount_minor");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_platform_revenues_split_basis_points') THEN
        ALTER TABLE "platform_revenues"
            ADD CONSTRAINT "chk_platform_revenues_split_basis_points"
            CHECK ("author_share_basis_points" + "platform_share_basis_points" + "safety_fund_share_basis_points" = 10000);
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS "safety_fund_allocations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_purchase_id" bigint NOT NULL,
    "payment_id" bigint NULL,
    "article_id" bigint NOT NULL,
    "policy_id" bigint NOT NULL,
    "base_amount_minor" bigint NOT NULL,
    "safety_fund_amount_minor" bigint NOT NULL,
    "safety_fund_basis_points" integer NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "ledger_transaction_id" bigint NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_safety_fund_allocation_purchase" UNIQUE ("article_purchase_id"),
    CONSTRAINT "uq_safety_fund_allocation_ledger" UNIQUE ("ledger_transaction_id"),
    CONSTRAINT "chk_safety_fund_allocation_amount" CHECK ("base_amount_minor" > 0 AND "safety_fund_amount_minor" >= 0),
    CONSTRAINT "chk_safety_fund_allocation_basis_points" CHECK ("safety_fund_basis_points" BETWEEN 0 AND 10000),
    CONSTRAINT "fk_safety_fund_allocation_purchase" FOREIGN KEY ("article_purchase_id") REFERENCES "article_purchases" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_safety_fund_allocation_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_safety_fund_allocation_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_safety_fund_allocation_policy" FOREIGN KEY ("policy_id") REFERENCES "revenue_split_policies" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_safety_fund_allocation_ledger" FOREIGN KEY ("ledger_transaction_id") REFERENCES "wallet_transactions" ("id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "idx_safety_fund_allocations_created"
ON "safety_fund_allocations" ("created_at" DESC, "id" DESC);

CREATE TABLE IF NOT EXISTS "safety_fund_disbursements" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "public_id" varchar(36) NOT NULL,
    "amount_minor" bigint NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "category" varchar(40) NOT NULL,
    "description" varchar(500) NOT NULL,
    "evidence_reference" varchar(255) NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'executed',
    "requested_by" bigint NULL,
    "approval_request_public_id" varchar(36) NOT NULL,
    "ledger_transaction_id" bigint NOT NULL,
    "balance_before_minor" bigint NOT NULL,
    "balance_after_minor" bigint NOT NULL,
    "requested_at" timestamp without time zone NOT NULL,
    "executed_at" timestamp without time zone NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_safety_fund_disbursement_public" UNIQUE ("public_id"),
    CONSTRAINT "uq_safety_fund_disbursement_request" UNIQUE ("approval_request_public_id"),
    CONSTRAINT "uq_safety_fund_disbursement_ledger" UNIQUE ("ledger_transaction_id"),
    CONSTRAINT "chk_safety_fund_disbursement_amount" CHECK ("amount_minor" > 0),
    CONSTRAINT "chk_safety_fund_disbursement_balance" CHECK ("balance_after_minor" >= 0),
    CONSTRAINT "chk_safety_fund_disbursement_status" CHECK ("status" IN ('executed','reversed')),
    CONSTRAINT "chk_safety_fund_disbursement_category" CHECK ("category" IN ('legal_help','proceedings','expertise','materials_protection','other')),
    CONSTRAINT "fk_safety_fund_disbursement_requested_by" FOREIGN KEY ("requested_by") REFERENCES "users" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_safety_fund_disbursement_ledger" FOREIGN KEY ("ledger_transaction_id") REFERENCES "wallet_transactions" ("id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "idx_safety_fund_disbursements_created"
ON "safety_fund_disbursements" ("created_at" DESC, "id" DESC);

UPDATE "security_mobile_operation_policies"
SET "policy" = 'mobile', "enforced" = 1, "application_variant" = 'admin', "updated_at" = NOW()
WHERE "action_type" IN ('financial_settings.change', 'safety_fund.disbursement');
