-- ETAP 6: trwałe kolejki workerów, leasing, idempotencja i dead-letter.

CREATE TABLE IF NOT EXISTS "background_jobs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL UNIQUE,
    "queue_name" varchar(80) NOT NULL,
    "job_type" varchar(100) NOT NULL,
    "status" varchar(24) NOT NULL DEFAULT 'queued'
        CHECK ("status" IN ('queued','running','retry','completed','dead_letter','rejected','cancelled')),
    "priority" integer NOT NULL DEFAULT 0,
    "payload_json" jsonb NOT NULL,
    "result_json" jsonb NULL,
    "idempotency_key" varchar(190) NOT NULL,
    "actor_user_id" bigint NULL,
    "required_permission" varchar(100) NULL,
    "request_id" varchar(100) NULL,
    "actor_ip" varchar(64) NULL,
    "retry_policy" varchar(16) NOT NULL DEFAULT 'automatic'
        CHECK ("retry_policy" IN ('automatic','manual')),
    "attempts" integer NOT NULL DEFAULT 0 CHECK ("attempts" >= 0),
    "max_attempts" integer NOT NULL DEFAULT 5 CHECK ("max_attempts" BETWEEN 1 AND 20),
    "available_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lease_expires_at" timestamp without time zone NULL,
    "locked_by" varchar(100) NULL,
    "last_error" text NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" timestamp without time zone NULL,
    "completed_at" timestamp without time zone NULL,
    "dead_lettered_at" timestamp without time zone NULL,
    CONSTRAINT "uq_background_jobs_idempotency" UNIQUE ("queue_name","idempotency_key"),
    CONSTRAINT "fk_background_jobs_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_background_jobs_claim"
    ON "background_jobs" ("queue_name","status","priority" DESC,"available_at","id");
CREATE INDEX IF NOT EXISTS "idx_background_jobs_lease"
    ON "background_jobs" ("status","lease_expires_at");

CREATE TABLE IF NOT EXISTS "background_job_events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "background_job_id" bigint NOT NULL,
    "event_type" varchar(50) NOT NULL,
    "from_status" varchar(24) NULL,
    "to_status" varchar(24) NOT NULL,
    "worker_id" varchar(100) NULL,
    "details_json" jsonb NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_background_job_events_job" FOREIGN KEY ("background_job_id") REFERENCES "background_jobs" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_background_job_events_job"
    ON "background_job_events" ("background_job_id","created_at");

CREATE TABLE IF NOT EXISTS "scheduler_runs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "task_name" varchar(100) NOT NULL,
    "scheduled_for" timestamp without time zone NOT NULL,
    "status" varchar(16) NOT NULL CHECK ("status" IN ('running','completed','failed')),
    "result_json" jsonb NULL,
    "error" text NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" timestamp without time zone NULL,
    CONSTRAINT "uq_scheduler_runs_slot" UNIQUE ("task_name","scheduled_for")
);

ALTER TABLE "mail_queue" ADD COLUMN IF NOT EXISTS "idempotency_key" varchar(190);
ALTER TABLE "mail_queue" ADD COLUMN IF NOT EXISTS "dead_lettered_at" timestamp without time zone;
UPDATE "mail_queue" SET "idempotency_key"='legacy-mail:' || "id" WHERE "idempotency_key" IS NULL;
ALTER TABLE "mail_queue" ALTER COLUMN "idempotency_key" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_mail_queue_idempotency" ON "mail_queue" ("idempotency_key");

ALTER TABLE "mail_queue" DROP CONSTRAINT IF EXISTS "mail_queue_status_check";
ALTER TABLE "mail_queue" ADD CONSTRAINT "mail_queue_status_check"
    CHECK ("status" IN ('queued','sending','retry','sent','failed','dead_letter','cancelled'));
