-- 3DORS Wartownik: observation, alert lifecycle and explicit application-instance freshness.
-- Historical security_events stay immutable. Alerts are separate operational records.

CREATE TABLE IF NOT EXISTS "security_alerts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL,
    "source_event_id" bigint NOT NULL,
    "severity" varchar(16) NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'open',
    "opened_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "acknowledged_at" timestamp without time zone NULL,
    "acknowledged_by" bigint NULL,
    "resolved_at" timestamp without time zone NULL,
    "resolved_by" bigint NULL,
    "resolution_note" text NULL,
    "status_changed_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "uq_security_alerts_public_id" UNIQUE ("public_id"),
    CONSTRAINT "uq_security_alerts_source_event" UNIQUE ("source_event_id"),
    CONSTRAINT "security_alerts_severity" CHECK ("severity" IN ('high','critical')),
    CONSTRAINT "security_alerts_status" CHECK ("status" IN ('open','acknowledged','resolved')),
    CONSTRAINT "fk_security_alerts_source_event" FOREIGN KEY ("source_event_id") REFERENCES "security_events" ("id") ON DELETE RESTRICT,
    CONSTRAINT "fk_security_alerts_acknowledged_by" FOREIGN KEY ("acknowledged_by") REFERENCES "users" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_security_alerts_resolved_by" FOREIGN KEY ("resolved_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_security_alerts_status_severity_time"
ON "security_alerts" ("status", "severity", "opened_at" DESC);

-- The activation watermark prevents the scheduler from turning historical events into
-- a notification storm when Wartownik is first deployed. Historical events remain
-- searchable, but only events created from this cutover forward become alerts.
CREATE TABLE IF NOT EXISTS "security_sentinel_state" (
    "singleton_id" smallint PRIMARY KEY DEFAULT 1,
    "activated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_sentinel_state_singleton" CHECK ("singleton_id" = 1)
);

INSERT INTO "security_sentinel_state" ("singleton_id", "activated_at", "created_at")
VALUES (1, NOW(), NOW())
ON CONFLICT ("singleton_id") DO NOTHING;

CREATE TABLE IF NOT EXISTS "security_alert_transitions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "alert_id" bigint NOT NULL,
    "from_status" varchar(20) NOT NULL,
    "to_status" varchar(20) NOT NULL,
    "actor_id" bigint NOT NULL,
    "reason" varchar(500) NOT NULL,
    "request_id" varchar(64) NULL,
    "correlation_id" varchar(128) NULL,
    "instance_id" varchar(80) NULL,
    "occurred_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_alert_transitions_from" CHECK ("from_status" IN ('open','acknowledged','resolved')),
    CONSTRAINT "security_alert_transitions_to" CHECK ("to_status" IN ('acknowledged','resolved')),
    CONSTRAINT "fk_security_alert_transitions_alert" FOREIGN KEY ("alert_id") REFERENCES "security_alerts" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_security_alert_transitions_actor" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "idx_security_alert_transitions_alert_time"
ON "security_alert_transitions" ("alert_id", "occurred_at" DESC);

CREATE TABLE IF NOT EXISTS "security_alert_notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "alert_id" bigint NOT NULL,
    "recipient_user_id" bigint NOT NULL,
    "channel" varchar(20) NOT NULL DEFAULT 'email',
    "status" varchar(20) NOT NULL DEFAULT 'pending',
    "attempts" integer NOT NULL DEFAULT 0,
    "next_attempt_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "locked_at" timestamp without time zone NULL,
    "mail_queue_id" bigint NULL,
    "queued_at" timestamp without time zone NULL,
    "last_error" varchar(1000) NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "uq_security_alert_notifications_recipient" UNIQUE ("alert_id", "recipient_user_id", "channel"),
    CONSTRAINT "security_alert_notifications_channel" CHECK ("channel" IN ('email')),
    CONSTRAINT "security_alert_notifications_status" CHECK ("status" IN ('pending','processing','queued','failed')),
    CONSTRAINT "security_alert_notifications_attempts" CHECK ("attempts" >= 0),
    CONSTRAINT "fk_security_alert_notifications_alert" FOREIGN KEY ("alert_id") REFERENCES "security_alerts" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_security_alert_notifications_user" FOREIGN KEY ("recipient_user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_security_alert_notifications_dispatch"
ON "security_alert_notifications" ("status", "next_attempt_at", "id");

CREATE TABLE IF NOT EXISTS "security_instance_heartbeats" (
    "instance_id" varchar(80) PRIMARY KEY,
    "instance_role" varchar(32) NOT NULL DEFAULT 'application',
    "expected" boolean NOT NULL DEFAULT FALSE,
    "ready" boolean NOT NULL DEFAULT FALSE,
    "last_seen_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "last_ready_at" timestamp without time zone NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "security_instance_heartbeats_role" CHECK ("instance_role" IN ('application','worker','scheduler'))
);

CREATE INDEX IF NOT EXISTS "idx_security_instance_heartbeats_expected_seen"
ON "security_instance_heartbeats" ("expected", "last_seen_at" DESC);

ALTER TABLE "security_events"
ALTER COLUMN "correlation_id" TYPE varchar(128);

CREATE INDEX IF NOT EXISTS "idx_security_events_risk_result_time"
ON "security_events" ("risk_level", "result", "occurred_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_security_events_correlation_time"
ON "security_events" ("correlation_id", "occurred_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_security_events_request_time"
ON "security_events" ("request_id", "occurred_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_security_events_instance_time"
ON "security_events" ("instance_id", "occurred_at" DESC);
