-- Spójny model kampanii efektowych oraz zgłoszeń błędów.

UPDATE "campaigns" SET "type"='ad_view' WHERE "type"='display_ad';

ALTER TABLE "campaigns"
    ADD COLUMN IF NOT EXISTS "placement" varchar(40) NOT NULL DEFAULT 'campaigns',
    ADD COLUMN IF NOT EXISTS "creative_path" varchar(500) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "creative_mime" varchar(120) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "linked_article_id" bigint DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "linked_survey_id" bigint DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "minimum_view_seconds" integer NOT NULL DEFAULT 15;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='campaigns_placement') THEN
        ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_placement"
            CHECK ("placement" IN ('home','article','campaigns'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='campaigns_minimum_view_seconds') THEN
        ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_minimum_view_seconds"
            CHECK ("minimum_view_seconds" BETWEEN 1 AND 600);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_campaign_linked_article') THEN
        ALTER TABLE "campaigns" ADD CONSTRAINT "fk_campaign_linked_article"
            FOREIGN KEY ("linked_article_id") REFERENCES "articles" ("id") ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_campaign_linked_survey') THEN
        ALTER TABLE "campaigns" ADD CONSTRAINT "fk_campaign_linked_survey"
            FOREIGN KEY ("linked_survey_id") REFERENCES "surveys" ("id") ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_campaigns_active_placement"
ON "campaigns" ("placement","status","starts_at","ends_at");

CREATE INDEX IF NOT EXISTS "idx_campaigns_linked_article"
ON "campaigns" ("linked_article_id") WHERE "linked_article_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_campaigns_linked_survey"
ON "campaigns" ("linked_survey_id") WHERE "linked_survey_id" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "campaign_delivery_events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "campaign_id" bigint NOT NULL REFERENCES "campaigns" ("id") ON DELETE CASCADE,
    "user_id" bigint DEFAULT NULL REFERENCES "users" ("id") ON DELETE SET NULL,
    "session_hash" char(64) NOT NULL,
    "event_type" varchar(20) NOT NULL CHECK ("event_type" IN ('impression','start')),
    "event_date" date NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uq_campaign_delivery_daily" UNIQUE ("campaign_id","session_hash","event_type","event_date")
);

CREATE INDEX IF NOT EXISTS "idx_campaign_delivery_report"
ON "campaign_delivery_events" ("campaign_id","event_type","created_at" DESC);

CREATE TABLE IF NOT EXISTS "bug_reports" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(36) NOT NULL UNIQUE,
    "user_id" bigint DEFAULT NULL REFERENCES "users" ("id") ON DELETE SET NULL,
    "page_url" varchar(1000) NOT NULL,
    "description" text NOT NULL,
    "details" text DEFAULT NULL,
    "attachment_path" varchar(500) DEFAULT NULL,
    "attachment_mime" varchar(120) DEFAULT NULL,
    "status" varchar(24) NOT NULL DEFAULT 'submitted' CHECK ("status" IN ('submitted','accepted','rejected')),
    "reward_qualified" boolean DEFAULT NULL,
    "reward_points" integer DEFAULT NULL CHECK ("reward_points" IS NULL OR "reward_points" BETWEEN 0 AND 1000000),
    "reward_job_public_id" varchar(36) DEFAULT NULL REFERENCES "background_jobs" ("public_id") ON DELETE RESTRICT,
    "review_note" text DEFAULT NULL,
    "reviewed_by_admin_id" bigint DEFAULT NULL REFERENCES "users" ("id") ON DELETE SET NULL,
    "reviewed_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_bug_reports_status_created"
ON "bug_reports" ("status","created_at" DESC);

-- Martwe reguły pozostają w historii, ale nie mogą przypadkiem wrócić jako aktywne.
UPDATE "activity_reward_rules"
SET "is_active"=0,"points_amount"=0,"amount_minor"=0,"daily_limit"=0,"updated_at"=NOW()
WHERE "activity_type" IN (
    'login_bonus','share_bonus','link_click_bonus','like_bonus',
    'sponsored_article_read_bonus','newsletter_open_reward','ppv_reward','live_event_reward'
);
