<?php
declare(strict_types=1);

/**
 * Każda tabela źródłowa ma jawną decyzję. Importer odmawia pracy, gdy w MySQL
 * pojawi się tabela, której nie ma w tym manifeście.
 */
return [
    'version' => 1,
    'source_admin_id' => 4,
    'source_admin_legacy_id' => 8,
    'financial_approval' => 'controlled_admin_wallet_chain_opening',
    'opening_points' => 129362,
    'presentation_settings' => [
        'site.name',
        'site.tagline',
        'premium_access_hours',
        'publisher_fee_percent',
    ],
    'tables' => [
        'activity_bonus_notifications' => 'skip',
        'activity_reward_logs' => 'skip',
        'activity_reward_rules' => 'skip',
        'ad_clicks' => 'skip',
        'ad_views' => 'skip',
        'admin_audit_logs' => 'skip',
        'ai_budget_periods' => 'skip',
        'ai_job_events' => 'skip',
        'ai_jobs' => 'skip',
        'ai_prompt_templates' => 'skip',
        'article_access_grants' => 'skip',
        'article_categories' => 'copy_selected',
        'article_events' => 'copy_transform',
        'article_purchases' => 'skip',
        'article_reads' => 'skip',
        'article_supports' => 'skip',
        'article_translation_versions' => 'copy_transform',
        'article_translations' => 'copy_transform',
        'article_versions' => 'copy_selected',
        'articles' => 'reassign_to_admin',
        'auth_login_events' => 'skip',
        'campaign_events' => 'skip',
        'campaigns' => 'copy_transform',
        'categories' => 'copy_selected',
        'category_translations' => 'copy_selected',
        'donation_campaigns' => 'skip',
        'donations' => 'skip',
        'email_verification_tokens' => 'skip',
        'finance_balance_reports' => 'skip',
        'finance_import_errors' => 'skip',
        'finance_import_runs' => 'skip',
        'finance_legacy_events' => 'skip',
        'finance_legacy_wallet_snapshots' => 'skip',
        'financial_approvals' => 'skip',
        'financial_audit_log' => 'skip',
        'financial_ledger_head' => 'rebuild',
        'fraud_events' => 'skip',
        'legacy_edd_product_map' => 'skip',
        'live_events' => 'skip',
        'mail_queue' => 'skip',
        'main_banner_translations' => 'copy_selected',
        'main_banners' => 'copy_selected',
        'media' => 'copy_transform',
        'password_resets' => 'skip',
        'payment_events' => 'skip',
        'payment_gateway_events' => 'skip',
        'payment_items' => 'skip',
        'payment_orders' => 'skip',
        'payment_webhook_events' => 'skip',
        'payments' => 'skip',
        'payout_methods' => 'skip',
        'payout_status_logs' => 'skip',
        'payouts' => 'skip',
        'platform_revenues' => 'skip',
        'ppv_events' => 'skip',
        'schema_migrations' => 'skip',
        'sessions' => 'skip',
        'settings' => 'copy_selected',
        'sponsored_article_reads' => 'skip',
        'survey_questions' => 'copy_selected',
        'survey_reports' => 'skip',
        'survey_response_items' => 'skip',
        'survey_responses' => 'skip',
        'surveys' => 'copy_transform',
        'user_activity_events' => 'skip',
        'user_delete_reports' => 'skip',
        'user_oauth_accounts' => 'skip',
        'user_profiles' => 'copy_selected',
        'user_roles' => 'rebuild',
        'users' => 'copy_transform',
        'wallet_price_packages' => 'skip',
        'wallet_topup_packages' => 'skip',
        'wallet_transactions' => 'rebuild',
        'wallet_transfers' => 'skip',
        'wallets' => 'rebuild',
    ],
    'target_only_tables' => [
        'background_job_events',
        'background_jobs',
        'financial_ledger_anchors',
        'financial_ledger_migration_state',
        'financial_operations',
        'financial_wallet_ledger_heads',
        'scheduler_runs',
        'selected_migration_article_authors',
        'selected_migration_legacy_wallet_transactions',
        'selected_migration_runs',
    ],
];
