-- Wygenerowano z database/zrodlo_slowa.sql.
-- Nie edytuj ręcznie; użyj scripts/dev/convert_mysql_schema_to_postgresql.php.
-- Baseline zachowuje dotychczasowy globalny łańcuch księgi. Jego zmiana nie jest
-- częścią migracji PostgreSQL i wymaga osobnego uzgodnienia sald.

SET client_encoding = 'UTF8';
SET TIME ZONE 'UTC';
SET lock_timeout = '10s';
SET statement_timeout = '120s';

BEGIN;

CREATE TABLE "activity_bonus_notifications" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "activity_type" varchar(50) NOT NULL,
    "amount_minor" bigint NOT NULL DEFAULT '0',
    "points_amount" integer NOT NULL DEFAULT '0',
    "message" varchar(255) NOT NULL,
    "title_key" varchar(160) DEFAULT NULL,
    "message_key" varchar(160) DEFAULT NULL,
    "description_key" varchar(160) DEFAULT NULL,
    "reference_type" varchar(50) DEFAULT NULL,
    "reference_id" bigint DEFAULT NULL,
    "seen_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "activity_reward_logs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "activity_type" varchar(50) NOT NULL,
    "reference_type" varchar(50) DEFAULT NULL,
    "reference_id" bigint DEFAULT NULL,
    "points_amount" integer NOT NULL,
    "amount_minor" bigint NOT NULL DEFAULT '0',
    "wallet_transaction_id" bigint DEFAULT NULL,
    "live_message" varchar(255) DEFAULT NULL,
    "title_key" varchar(160) DEFAULT NULL,
    "message_key" varchar(160) DEFAULT NULL,
    "description_key" varchar(160) DEFAULT NULL,
    "awarded_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "activity_reward_rules" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "activity_type" varchar(50) NOT NULL,
    "points_amount" integer NOT NULL DEFAULT '0',
    "amount_minor" bigint NOT NULL DEFAULT '0',
    "label" varchar(120) DEFAULT NULL,
    "live_message_template" varchar(255) DEFAULT NULL,
    "title_key" varchar(160) DEFAULT NULL,
    "message_key" varchar(160) DEFAULT NULL,
    "description_key" varchar(160) DEFAULT NULL,
    "daily_limit" integer NOT NULL DEFAULT '0',
    "is_active" smallint NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_activity_reward_rules_activity_type" UNIQUE ("activity_type")
);

CREATE TABLE "ad_clicks" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "campaign_id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "campaign_event_id" bigint NOT NULL,
    "clicked_at" timestamp without time zone NOT NULL,
    "target_url" varchar(500) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "ad_views" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "campaign_id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "campaign_event_id" bigint NOT NULL,
    "viewed_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "admin_audit_logs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint DEFAULT NULL,
    "action" varchar(120) NOT NULL,
    "payload" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "ai_budget_periods" (
    "period_start" date NOT NULL,
    "budget_minor" bigint NOT NULL,
    "reserved_minor" bigint NOT NULL DEFAULT '0',
    "spent_minor" bigint NOT NULL DEFAULT '0',
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("period_start")
);

CREATE TABLE "ai_job_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ai_job_id" bigint NOT NULL,
    "event_type" varchar(64) NOT NULL,
    "actor_user_id" bigint DEFAULT NULL,
    "status_from" varchar(32) DEFAULT NULL,
    "status_to" varchar(32) DEFAULT NULL,
    "message" varchar(255) DEFAULT NULL,
    "payload_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "ai_jobs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "public_id" varchar(64) NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "article_id" bigint DEFAULT NULL,
    "translation_id" bigint DEFAULT NULL,
    "type" varchar(64) NOT NULL,
    "provider" varchar(32) NOT NULL DEFAULT 'openai',
    "model" varchar(128) DEFAULT NULL,
    "status" varchar(32) NOT NULL DEFAULT 'draft',
    "prompt_code" varchar(96) DEFAULT NULL,
    "prompt_version" varchar(32) DEFAULT NULL,
    "input_hash" varchar(128) DEFAULT NULL,
    "input_json" jsonb DEFAULT NULL,
    "output_json" jsonb DEFAULT NULL,
    "error_message" text,
    "tokens_input" integer DEFAULT NULL,
    "tokens_output" integer DEFAULT NULL,
    "estimated_cost_minor" bigint NOT NULL DEFAULT '0',
    "actual_cost_minor" bigint NOT NULL DEFAULT '0',
    "budget_period" date DEFAULT NULL,
    "budget_status" text NOT NULL DEFAULT 'none' CHECK ("budget_status" IN ('none','reserved','spent','released')),
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "queued_at" timestamp without time zone DEFAULT NULL,
    "started_at" timestamp without time zone DEFAULT NULL,
    "completed_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_ai_jobs_public_id" UNIQUE ("public_id")
);

CREATE TABLE "ai_prompt_templates" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(96) NOT NULL,
    "name" varchar(160) NOT NULL,
    "name_key" varchar(160) DEFAULT NULL,
    "task_type" varchar(64) NOT NULL,
    "version" varchar(32) NOT NULL DEFAULT 'v1',
    "provider" varchar(32) NOT NULL DEFAULT 'openai',
    "model" varchar(128) DEFAULT NULL,
    "system_prompt" text NOT NULL,
    "user_template" text NOT NULL,
    "output_schema_json" jsonb DEFAULT NULL,
    "is_active" smallint NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_ai_prompt_templates_code" UNIQUE ("code")
);

CREATE TABLE "article_access_grants" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "article_id" bigint NOT NULL,
    "payment_id" bigint DEFAULT NULL,
    "status" text NOT NULL DEFAULT 'active' CHECK ("status" IN ('active','revoked','expired')),
    "revoked_at" timestamp without time zone DEFAULT NULL,
    "source" text NOT NULL DEFAULT 'payment' CHECK ("source" IN ('wallet','payment','legacy_edd','admin')),
    "granted_at" timestamp without time zone NOT NULL,
    "expires_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_article_access_grants_uq_aag_user_article" UNIQUE ("user_id","article_id")
);

CREATE TABLE "article_categories" (
    "article_id" bigint NOT NULL,
    "category_id" bigint NOT NULL,
    PRIMARY KEY ("article_id","category_id")
);

CREATE TABLE "article_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "event" varchar(80) NOT NULL,
    "payload_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "article_purchases" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_id" bigint NOT NULL,
    "buyer_user_id" bigint NOT NULL,
    "author_user_id" bigint NOT NULL,
    "payment_id" bigint DEFAULT NULL,
    "total_amount_minor" bigint NOT NULL,
    "author_amount_minor" bigint NOT NULL,
    "platform_amount_minor" bigint NOT NULL,
    "author_share_percent" decimal(5,2) NOT NULL DEFAULT '70.00',
    "platform_share_percent" decimal(5,2) NOT NULL DEFAULT '30.00',
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "status" text NOT NULL DEFAULT 'paid' CHECK ("status" IN ('paid','refunded','cancelled')),
    "access_granted_until" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_article_purchases_uq_article_purchase_buyer_article" UNIQUE ("buyer_user_id","article_id")
);

CREATE TABLE "article_reads" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "ip_hash" char(64) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "article_supports" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_id" bigint NOT NULL,
    "reader_id" bigint NOT NULL,
    "author_id" bigint NOT NULL,
    "payment_id" bigint NOT NULL,
    "amount_minor" bigint NOT NULL,
    "note" text,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "article_translations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_id" bigint NOT NULL,
    "language" varchar(10) NOT NULL DEFAULT 'en',
    "source_language" varchar(16) NOT NULL DEFAULT 'pl',
    "target_language" varchar(16) NOT NULL,
    "title" varchar(255) NOT NULL,
    "lead" text,
    "body" text NOT NULL,
    "seo_title" varchar(255) DEFAULT NULL,
    "seo_description" text,
    "seo_keywords" text,
    "slug" varchar(255) DEFAULT NULL,
    "status" varchar(50) NOT NULL DEFAULT 'draft',
    "translation_instructions" text,
    "ai_provider" varchar(100) DEFAULT NULL,
    "ai_model" varchar(100) DEFAULT NULL,
    "provider" varchar(32) DEFAULT NULL,
    "ai_job_id" bigint DEFAULT NULL,
    "created_by" bigint DEFAULT NULL,
    "updated_by" bigint DEFAULT NULL,
    "reviewed_by" bigint DEFAULT NULL,
    "published_by" bigint DEFAULT NULL,
    "published_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    "reviewed_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_article_translations_uniq_article_translation_lang" UNIQUE ("article_id","target_language")
);

CREATE TABLE "article_translation_versions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "translation_id" bigint NOT NULL,
    "version_no" bigint NOT NULL,
    "title" varchar(255) NOT NULL,
    "lead" text,
    "body" text NOT NULL,
    "seo_title" varchar(255) DEFAULT NULL,
    "seo_description" text,
    "seo_keywords" text,
    "slug" varchar(255) DEFAULT NULL,
    "status" varchar(50) NOT NULL,
    "translation_instructions" text,
    "changed_by" bigint DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_article_translation_versions_uniq_article_translati_f65fc221" UNIQUE ("translation_id","version_no")
);

CREATE TABLE "article_versions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_id" bigint NOT NULL,
    "title" varchar(255) NOT NULL,
    "lead" text,
    "body" text NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "articles" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_source" varchar(40) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "author_id" bigint NOT NULL,
    "title" varchar(255) NOT NULL,
    "slug" varchar(255) NOT NULL,
    "lead" text,
    "body" text NOT NULL,
    "status" text NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','submitted','review','approved','published','rejected','archived')),
    "access_mode" text NOT NULL DEFAULT 'free' CHECK ("access_mode" IN ('free','paid')),
    "price_minor" bigint NOT NULL DEFAULT '0',
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "is_premium" smallint NOT NULL DEFAULT '0',
    "is_unique" smallint NOT NULL DEFAULT '0',
    "pricing_status" text NOT NULL DEFAULT 'not_priced' CHECK ("pricing_status" IN ('not_priced','priced','free','blocked')),
    "author_share_percent" decimal(5,2) NOT NULL DEFAULT '70.00',
    "platform_share_percent" decimal(5,2) NOT NULL DEFAULT '30.00',
    "editor_valuation_note" text,
    "article_label" varchar(50) DEFAULT NULL,
    "valued_by_admin_id" bigint DEFAULT NULL,
    "valued_at" timestamp without time zone DEFAULT NULL,
    "published_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    "source_language" varchar(10) NOT NULL DEFAULT 'pl',
    "display_order" integer NOT NULL DEFAULT '0',
    "editorial_weight" integer NOT NULL DEFAULT '0',
    "is_featured" smallint NOT NULL DEFAULT '0',
    "revision_of_article_id" bigint DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "auth_login_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint DEFAULT NULL,
    "email" varchar(255) DEFAULT NULL,
    "result" varchar(32) NOT NULL,
    "ip_hash" varchar(128) DEFAULT NULL,
    "user_agent_hash" varchar(128) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "campaign_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "campaign_id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "event_type" text NOT NULL CHECK ("event_type" IN ('view','click','sponsored_read','ppv_purchase','live_join','survey_completed')),
    "event_date" date NOT NULL,
    "cost_minor" bigint NOT NULL DEFAULT '0',
    "reward_minor" bigint NOT NULL DEFAULT '0',
    "ip_hash" char(64) DEFAULT NULL,
    "user_agent" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "watch_seconds" integer NOT NULL DEFAULT '0',
    "is_rewarded" smallint NOT NULL DEFAULT '1',
    "fraud_risk_score" integer NOT NULL DEFAULT '0',
    "fraud_status" text NOT NULL DEFAULT 'normal' CHECK ("fraud_status" IN ('normal','observe','suspect','hold_payout')),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_campaign_events_uq_campaign_user_daily_event" UNIQUE ("campaign_id","user_id","event_type","event_date")
);

CREATE TABLE "campaigns" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "client_name" varchar(180) DEFAULT NULL,
    "name" varchar(220) NOT NULL,
    "type" text NOT NULL DEFAULT 'display_ad' CHECK ("type" IN ('ad_click','display_ad','sponsored_article','ad_view','ppv','live','survey_ad')),
    "description" text,
    "target_url" varchar(500) DEFAULT NULL,
    "budget_minor" bigint NOT NULL DEFAULT '0',
    "cost_per_view_minor" bigint NOT NULL DEFAULT '0',
    "cost_per_click_minor" bigint NOT NULL DEFAULT '0',
    "cost_per_completed_survey_minor" bigint NOT NULL DEFAULT '0',
    "reward_for_user_minor" bigint NOT NULL DEFAULT '0',
    "status" text NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','active','paused','closed')),
    "starts_at" timestamp without time zone DEFAULT NULL,
    "ends_at" timestamp without time zone DEFAULT NULL,
    "created_by_admin_id" bigint DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "categories" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_source" varchar(40) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "name" varchar(190) NOT NULL,
    "slug" varchar(190) NOT NULL,
    "type" varchar(40) NOT NULL DEFAULT 'category',
    "created_at" timestamp without time zone NOT NULL,
    "show_in_menu" smallint NOT NULL DEFAULT '1',
    "menu_order" integer NOT NULL DEFAULT '100',
    "is_active" smallint NOT NULL DEFAULT '1',
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_categories_uq_categories_slug" UNIQUE ("slug")
);

CREATE TABLE "category_translations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "category_id" bigint NOT NULL,
    "language" varchar(5) NOT NULL,
    "name" varchar(190) NOT NULL,
    "slug" varchar(190) NOT NULL,
    "description" text,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_category_translations_uq_category_language" UNIQUE ("category_id","language")
);

CREATE TABLE "donation_campaigns" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_id" bigint DEFAULT NULL,
    "name" varchar(190) NOT NULL,
    "slug" varchar(190) NOT NULL,
    "description" text,
    "target_amount_minor" bigint NOT NULL DEFAULT '0',
    "current_amount_minor" bigint NOT NULL DEFAULT '0',
    "active" smallint NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_donation_campaigns_uq_donation_campaign_slug" UNIQUE ("slug")
);

CREATE TABLE "donations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "payment_id" bigint NOT NULL,
    "campaign_id" bigint DEFAULT NULL,
    "campaign" varchar(190) NOT NULL,
    "target_amount_minor" bigint DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "email_verification_tokens" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "token_hash" varchar(128) NOT NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "used_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "finance_balance_reports" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "run_id" bigint DEFAULT NULL,
    "user_id" bigint NOT NULL,
    "legacy_wallet_id" bigint DEFAULT NULL,
    "legacy_points" bigint NOT NULL DEFAULT '0',
    "imported_points" bigint NOT NULL DEFAULT '0',
    "diff_points" bigint NOT NULL DEFAULT '0',
    "legacy_amount_minor" bigint NOT NULL DEFAULT '0',
    "imported_available_minor" bigint NOT NULL DEFAULT '0',
    "diff_minor" bigint NOT NULL DEFAULT '0',
    "status" text NOT NULL DEFAULT 'ok' CHECK ("status" IN ('ok','adjusted','missing_snapshot','error')),
    "note" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "finance_import_errors" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "run_id" bigint NOT NULL,
    "source_table" varchar(120) NOT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "message" text NOT NULL,
    "payload_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "finance_import_runs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "source" varchar(80) NOT NULL,
    "status" text NOT NULL DEFAULT 'started' CHECK ("status" IN ('started','finished','failed')),
    "summary_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "finished_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "finance_legacy_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "run_id" bigint DEFAULT NULL,
    "source_table" varchar(120) NOT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "ref_transaction_id" bigint DEFAULT NULL,
    "event_type" varchar(80) DEFAULT NULL,
    "status" varchar(80) DEFAULT NULL,
    "occurred_at" timestamp without time zone DEFAULT NULL,
    "payload_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_finance_legacy_events_uq_legacy_event" UNIQUE ("source_table","legacy_id")
);

CREATE TABLE "finance_legacy_wallet_snapshots" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "run_id" bigint DEFAULT NULL,
    "user_id" bigint NOT NULL,
    "legacy_wallet_id" bigint NOT NULL,
    "legacy_points" bigint NOT NULL,
    "legacy_amount_minor" bigint NOT NULL,
    "status" varchar(40) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_finance_legacy_wallet_snapshots_uq_legacy_wallet_snapshot" UNIQUE ("legacy_wallet_id")
);

CREATE TABLE "financial_ledger_head" (
    "id" smallint NOT NULL,
    "last_transaction_id" bigint DEFAULT NULL,
    "last_entry_hash" char(64) NOT NULL,
    "hash_version" integer NOT NULL DEFAULT '2',
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "financial_approvals" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "operation_type" varchar(50) NOT NULL,
    "operation_payload" jsonb NOT NULL,
    "amount" bigint NOT NULL,
    "currency" char(3) NOT NULL,
    "wallet_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "requested_by" bigint NOT NULL,
    "requested_role" varchar(50) NOT NULL,
    "approved_by" bigint DEFAULT NULL,
    "approved_role" varchar(50) DEFAULT NULL,
    "status" text NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending','approved','rejected','cancelled','executed','failed')),
    "reason" text,
    "admin_note" text,
    "reject_reason" text,
    "created_at" timestamp without time zone NOT NULL,
    "approved_at" timestamp without time zone DEFAULT NULL,
    "rejected_at" timestamp without time zone DEFAULT NULL,
    "executed_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "financial_audit_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "wallet_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "action" varchar(50) NOT NULL,
    "actor_id" bigint NOT NULL,
    "actor_role" varchar(50) NOT NULL,
    "amount" bigint NOT NULL,
    "before_json" jsonb DEFAULT NULL,
    "after_json" jsonb DEFAULT NULL,
    "context_json" jsonb DEFAULT NULL,
    "ip_address" varchar(45) DEFAULT NULL,
    "user_agent" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "fraud_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint DEFAULT NULL,
    "event_type" varchar(80) NOT NULL,
    "reference_type" varchar(80) DEFAULT NULL,
    "reference_id" bigint DEFAULT NULL,
    "risk_score" integer NOT NULL DEFAULT '0',
    "status" text NOT NULL DEFAULT 'normal' CHECK ("status" IN ('normal','observe','suspect','hold_payout')),
    "reasons_json" jsonb DEFAULT NULL,
    "ip_hash" char(64) DEFAULT NULL,
    "user_agent_hash" char(64) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "legacy_edd_product_map" (
    "edd_product_id" bigint NOT NULL,
    "target_type" text NOT NULL CHECK ("target_type" IN ('article','wallet_package','donation','donation_campaign')),
    "target_id" bigint DEFAULT NULL,
    "confidence" integer DEFAULT '100',
    "note" text,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("edd_product_id")
);

CREATE TABLE "live_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "campaign_id" bigint DEFAULT NULL,
    "title" varchar(220) NOT NULL,
    "description" text,
    "status" text NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','scheduled','live','ended')),
    "starts_at" timestamp without time zone DEFAULT NULL,
    "ends_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "mail_queue" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint DEFAULT NULL,
    "email" varchar(190) NOT NULL,
    "subject" varchar(255) NOT NULL,
    "body" text NOT NULL,
    "idempotency_key" varchar(190) NOT NULL,
    "status" text NOT NULL DEFAULT 'queued' CHECK ("status" IN ('queued','sending','retry','sent','failed','dead_letter','cancelled')),
    "attempts" bigint NOT NULL DEFAULT '0',
    "max_attempts" bigint NOT NULL DEFAULT '5',
    "available_at" timestamp without time zone NOT NULL,
    "locked_at" timestamp without time zone DEFAULT NULL,
    "locked_by" varchar(100) DEFAULT NULL,
    "error" text,
    "message_id" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    "sent_at" timestamp without time zone DEFAULT NULL,
    "failed_at" timestamp without time zone DEFAULT NULL,
    "dead_lettered_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_mail_queue_idempotency" UNIQUE ("idempotency_key")
);

CREATE TABLE "background_jobs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "public_id" varchar(36) NOT NULL,
    "queue_name" varchar(80) NOT NULL,
    "job_type" varchar(100) NOT NULL,
    "status" text NOT NULL DEFAULT 'queued' CHECK ("status" IN ('queued','running','retry','completed','dead_letter','rejected','cancelled')),
    "priority" integer NOT NULL DEFAULT '0',
    "payload_json" jsonb NOT NULL,
    "result_json" jsonb DEFAULT NULL,
    "idempotency_key" varchar(190) NOT NULL,
    "actor_user_id" bigint DEFAULT NULL,
    "required_permission" varchar(100) DEFAULT NULL,
    "request_id" varchar(100) DEFAULT NULL,
    "actor_ip" varchar(64) DEFAULT NULL,
    "retry_policy" text NOT NULL DEFAULT 'automatic' CHECK ("retry_policy" IN ('automatic','manual')),
    "attempts" integer NOT NULL DEFAULT '0' CHECK ("attempts" >= 0),
    "max_attempts" integer NOT NULL DEFAULT '5' CHECK ("max_attempts" BETWEEN 1 AND 20),
    "available_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lease_expires_at" timestamp without time zone DEFAULT NULL,
    "locked_by" varchar(100) DEFAULT NULL,
    "last_error" text,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" timestamp without time zone DEFAULT NULL,
    "completed_at" timestamp without time zone DEFAULT NULL,
    "dead_lettered_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_background_jobs_public_id" UNIQUE ("public_id"),
    CONSTRAINT "uq_background_jobs_idempotency" UNIQUE ("queue_name","idempotency_key")
);

CREATE TABLE "background_job_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "background_job_id" bigint NOT NULL,
    "event_type" varchar(50) NOT NULL,
    "from_status" varchar(24) DEFAULT NULL,
    "to_status" varchar(24) NOT NULL,
    "worker_id" varchar(100) DEFAULT NULL,
    "details_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "scheduler_runs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "task_name" varchar(100) NOT NULL,
    "scheduled_for" timestamp without time zone NOT NULL,
    "status" text NOT NULL CHECK ("status" IN ('running','completed','failed')),
    "result_json" jsonb DEFAULT NULL,
    "error" text,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_scheduler_runs_slot" UNIQUE ("task_name","scheduled_for")
);

CREATE TABLE "main_banner_translations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "banner_id" bigint NOT NULL,
    "language" varchar(8) NOT NULL,
    "kicker" varchar(255) DEFAULT NULL,
    "title" varchar(255) DEFAULT NULL,
    "lead_text" text,
    "body_text" text,
    "button_label" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_main_banner_translations_uq_main_banner_translations_lang" UNIQUE ("banner_id","language")
);

CREATE TABLE "main_banners" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "slug" varchar(80) NOT NULL DEFAULT 'home-main',
    "button_url" varchar(255) NOT NULL DEFAULT '/register',
    "image_path" varchar(255) NOT NULL DEFAULT '/assets/img/articles/hero-pier.svg',
    "is_active" smallint NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_main_banners_uq_main_banners_slug" UNIQUE ("slug")
);

CREATE TABLE "media" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_source" varchar(40) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "owner_user_id" bigint DEFAULT NULL,
    "article_id" bigint DEFAULT NULL,
    "path" varchar(255) NOT NULL,
    "mime" varchar(120) DEFAULT NULL,
    "title" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "image_position" integer DEFAULT '50',
    PRIMARY KEY ("id")
);

CREATE TABLE "password_resets" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "token_hash" char(64) NOT NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "used_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_password_resets_uq_password_resets_token" UNIQUE ("token_hash")
);

CREATE TABLE "payment_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "payment_id" bigint NOT NULL,
    "event_type" varchar(80) NOT NULL,
    "payload_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "payment_gateway_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "provider" varchar(32) NOT NULL,
    "event_id" varchar(255) NOT NULL,
    "event_type" varchar(128) NOT NULL,
    "payment_order_id" bigint DEFAULT NULL,
    "stripe_session_id" varchar(255) DEFAULT NULL,
    "stripe_payment_intent_id" varchar(255) DEFAULT NULL,
    "received_at" timestamp without time zone NOT NULL,
    "processed_at" timestamp without time zone DEFAULT NULL,
    "processing_status" varchar(32) NOT NULL DEFAULT 'received',
    "payload_json" jsonb DEFAULT NULL,
    "error_message" text,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_payment_gateway_events_uniq_provider_event" UNIQUE ("provider","event_id")
);

CREATE TABLE "payment_items" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "payment_id" bigint NOT NULL,
    "legacy_source" varchar(80) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "item_type" varchar(80) NOT NULL,
    "item_id" bigint DEFAULT NULL,
    "title" varchar(255) NOT NULL,
    "quantity" integer NOT NULL DEFAULT '1',
    "amount_minor" bigint NOT NULL,
    "raw_json" jsonb DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "payment_orders" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "public_id" varchar(64) NOT NULL,
    "user_id" bigint NOT NULL,
    "provider" varchar(32) NOT NULL,
    "method" varchar(32) DEFAULT NULL,
    "type" varchar(64) NOT NULL,
    "status" varchar(32) NOT NULL,
    "amount_minor" bigint NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "topup_package_id" bigint DEFAULT NULL,
    "stripe_session_id" varchar(255) DEFAULT NULL,
    "stripe_payment_intent_id" varchar(255) DEFAULT NULL,
    "idempotency_key" varchar(128) NOT NULL,
    "credited_at" timestamp without time zone DEFAULT NULL,
    "expires_at" timestamp without time zone DEFAULT NULL,
    "metadata_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_payment_orders_public_id" UNIQUE ("public_id"),
    CONSTRAINT "uq_payment_orders_idempotency_key" UNIQUE ("idempotency_key")
);

CREATE TABLE "payment_webhook_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "provider" varchar(80) NOT NULL,
    "external_id" varchar(190) DEFAULT NULL,
    "event_type" varchar(120) NOT NULL,
    "payload_json" jsonb DEFAULT NULL,
    "processed_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_payment_webhook_events_uq_payment_webhook_event" UNIQUE ("provider","external_id","event_type")
);

CREATE TABLE "payments" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_source" varchar(80) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "user_id" bigint DEFAULT NULL,
    "provider" varchar(60) NOT NULL,
    "provider_status" varchar(80) DEFAULT NULL,
    "type" text NOT NULL CHECK ("type" IN ('donation','wallet_topup','article_payment')),
    "status" text NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending','paid','failed','refunded','cancelled')),
    "amount_minor" bigint NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "payer_email" varchar(190) DEFAULT NULL,
    "external_id" varchar(190) DEFAULT NULL,
    "payment_key" varchar(190) DEFAULT NULL,
    "mode" varchar(40) DEFAULT NULL,
    "note" text,
    "raw_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "completed_at" timestamp without time zone DEFAULT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "payout_methods" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "type" text NOT NULL DEFAULT 'manual' CHECK ("type" IN ('bank','blik','paypal','manual')),
    "label" varchar(120) NOT NULL,
    "account_ref" varchar(255) NOT NULL,
    "is_default" smallint NOT NULL DEFAULT '0',
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "payout_status_logs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "payout_id" bigint NOT NULL,
    "from_status" varchar(40) DEFAULT NULL,
    "to_status" varchar(40) NOT NULL,
    "changed_by_user_id" bigint DEFAULT NULL,
    "note" text,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "payouts" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "payout_method_id" bigint DEFAULT NULL,
    "amount_minor" bigint NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "status" text NOT NULL DEFAULT 'requested' CHECK ("status" IN ('requested','approved','paid','rejected','cancelled')),
    "note" text,
    "admin_note" text,
    "requested_at" timestamp without time zone NOT NULL,
    "approved_at" timestamp without time zone DEFAULT NULL,
    "paid_at" timestamp without time zone DEFAULT NULL,
    "rejected_at" timestamp without time zone DEFAULT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    "fraud_risk_score" integer NOT NULL DEFAULT '0',
    "fraud_status" text NOT NULL DEFAULT 'normal' CHECK ("fraud_status" IN ('normal','observe','suspect','hold_payout')),
    "fraud_checked_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "platform_revenues" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "payment_id" bigint DEFAULT NULL,
    "article_id" bigint DEFAULT NULL,
    "buyer_user_id" bigint DEFAULT NULL,
    "author_user_id" bigint DEFAULT NULL,
    "total_amount_minor" bigint NOT NULL,
    "author_income_minor" bigint NOT NULL,
    "publisher_fee_minor" bigint NOT NULL,
    "publisher_fee_percent" decimal(5,2) NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "ppv_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "campaign_id" bigint DEFAULT NULL,
    "title" varchar(220) NOT NULL,
    "description" text,
    "price_minor" bigint NOT NULL DEFAULT '0',
    "status" text NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','active','closed')),
    "starts_at" timestamp without time zone DEFAULT NULL,
    "ends_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "sessions" (
    "id" varchar(128) NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "payload" text NOT NULL,
    "last_activity" integer NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "settings" (
    "name" varchar(120) NOT NULL,
    "value" text,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("name")
);

CREATE TABLE "sponsored_article_reads" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "campaign_id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "campaign_event_id" bigint NOT NULL,
    "article_id" bigint DEFAULT NULL,
    "read_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "survey_questions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "survey_id" bigint NOT NULL,
    "question_text" text NOT NULL,
    "question_type" text NOT NULL DEFAULT 'single_choice' CHECK ("question_type" IN ('single_choice','multiple_choice','text')),
    "options_json" jsonb DEFAULT NULL,
    "sort_order" integer NOT NULL DEFAULT '0',
    "is_required" smallint NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "survey_reports" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "survey_id" bigint NOT NULL,
    "generated_by_admin_id" bigint DEFAULT NULL,
    "title" varchar(220) NOT NULL,
    "summary_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "survey_response_items" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "response_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "answer_text" text,
    "answer_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "survey_responses" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "survey_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "reward_amount_minor" bigint NOT NULL DEFAULT '0',
    "reward_status" text NOT NULL DEFAULT 'pending' CHECK ("reward_status" IN ('pending','paid','blocked')),
    "wallet_transaction_id" bigint DEFAULT NULL,
    "completed_at" timestamp without time zone NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "answer_seconds" integer NOT NULL DEFAULT '0',
    "ip_hash" char(64) DEFAULT NULL,
    "user_agent_hash" char(64) DEFAULT NULL,
    "fraud_risk_score" integer NOT NULL DEFAULT '0',
    "fraud_status" text NOT NULL DEFAULT 'normal' CHECK ("fraud_status" IN ('normal','observe','suspect','hold_payout')),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_survey_responses_uq_survey_response_user" UNIQUE ("survey_id","user_id")
);

CREATE TABLE "surveys" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(220) NOT NULL,
    "description" text,
    "type" text NOT NULL DEFAULT 'editorial' CHECK ("type" IN ('consumer','political_poll','social_poll','local_poll','advertising','editorial','market_research')),
    "client_name" varchar(180) DEFAULT NULL,
    "budget_minor" bigint NOT NULL DEFAULT '0',
    "reward_amount_minor" bigint NOT NULL DEFAULT '0',
    "max_responses" bigint DEFAULT NULL,
    "status" text NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','active','paused','closed')),
    "starts_at" timestamp without time zone DEFAULT NULL,
    "ends_at" timestamp without time zone DEFAULT NULL,
    "created_by_admin_id" bigint DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_activity_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "activity_type" varchar(50) NOT NULL,
    "reference_type" varchar(50) DEFAULT NULL,
    "reference_id" bigint DEFAULT NULL,
    "note" text,
    "ip_hash" char(64) DEFAULT NULL,
    "user_agent" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_delete_reports" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "deleted_user_id" bigint NOT NULL,
    "deleted_by_admin_id" bigint DEFAULT NULL,
    "mode" text NOT NULL DEFAULT 'report' CHECK ("mode" IN ('report','deactivate','anonymize','hard_clean')),
    "summary_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_oauth_accounts" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "provider" text NOT NULL CHECK ("provider" IN ('google','apple')),
    "provider_user_id" varchar(255) NOT NULL,
    "provider_email" varchar(190) DEFAULT NULL,
    "provider_email_verified" smallint NOT NULL DEFAULT '0',
    "provider_name" varchar(255) DEFAULT NULL,
    "provider_avatar_url" varchar(2048) DEFAULT NULL,
    "linked_at" timestamp without time zone NOT NULL,
    "last_login_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_user_oauth_accounts_provider" UNIQUE ("provider","provider_user_id")
);

CREATE TABLE "user_profiles" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "bio" text,
    "avatar_path" varchar(255) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_roles" (
    "user_id" bigint NOT NULL,
    "role" varchar(64) NOT NULL,
    PRIMARY KEY ("user_id","role")
);

CREATE TABLE "users" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_source" varchar(40) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "login_name" varchar(64) DEFAULT NULL,
    "email" varchar(190) NOT NULL,
    "phone" varchar(60) DEFAULT NULL,
    "password_hash" varchar(255) NOT NULL,
    "display_name" varchar(190) NOT NULL,
    "status" text NOT NULL DEFAULT 'active' CHECK ("status" IN ('active','inactive','suspended','blocked','pending','pending_author','rejected','deleted')),
    "can_write" smallint NOT NULL DEFAULT '0',
    "talent_enabled" smallint NOT NULL DEFAULT '0',
    "wallet_enabled" smallint NOT NULL DEFAULT '0',
    "payout_enabled" smallint NOT NULL DEFAULT '0',
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    "permissions_updated_at" timestamp without time zone DEFAULT NULL,
    "deleted_at" timestamp without time zone DEFAULT NULL,
    "deleted_by_admin_id" bigint DEFAULT NULL,
    "deletion_mode" text NOT NULL DEFAULT 'none' CHECK ("deletion_mode" IN ('none','anonymized','hard_clean')),
    "anonymized_at" timestamp without time zone DEFAULT NULL,
    "email_verified_at" timestamp without time zone DEFAULT NULL,
    "two_factor_enabled" smallint NOT NULL DEFAULT '0',
    "two_factor_secret" varchar(128) DEFAULT NULL,
    "auth_security_level" varchar(32) NOT NULL DEFAULT 'basic',
    "force_2fa_setup" smallint NOT NULL DEFAULT '0',
    "force_password_change" smallint NOT NULL DEFAULT '0',
    "last_login_at" timestamp without time zone DEFAULT NULL,
    "last_login_ip_hash" varchar(128) DEFAULT NULL,
    "session_version" bigint NOT NULL DEFAULT '0',
    "display_currency" varchar(10) NOT NULL DEFAULT 'AUTO',
    "interface_language" varchar(5) DEFAULT NULL,
    "avatar_path" varchar(255) DEFAULT NULL,
    "avatar_updated_at" timestamp without time zone DEFAULT NULL,
    "article_submit_blocked_until" timestamp without time zone DEFAULT NULL,
    "article_submit_block_reason" text,
    "article_submit_blocked_by" bigint DEFAULT NULL,
    "article_submit_blocked_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_users_email" UNIQUE ("email")
);

CREATE TABLE "wallet_price_packages" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "legacy_source" varchar(80) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "points" bigint NOT NULL,
    "amount_minor" bigint NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "active" smallint NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_wallet_price_packages_uq_wallet_price_package" UNIQUE ("points","amount_minor","currency")
);

CREATE TABLE "wallet_topup_packages" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(128) NOT NULL,
    "description" varchar(255) DEFAULT NULL,
    "amount_minor" bigint NOT NULL,
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "talent_amount" bigint DEFAULT NULL,
    "is_active" smallint NOT NULL DEFAULT '1',
    "sort_order" integer NOT NULL DEFAULT '0',
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_wallet_topup_packages_code" UNIQUE ("code")
);

CREATE TABLE "wallet_transactions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "wallet_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "source_module" varchar(40) NOT NULL DEFAULT 'system',
    "type" varchar(80) NOT NULL,
    "account_type" text NOT NULL DEFAULT 'slowo' CHECK ("account_type" IN ('main','slowo','points')),
    "status" text NOT NULL DEFAULT 'posted' CHECK ("status" IN ('pending','posted','reserved','cancelled','failed')),
    "amount_minor" bigint NOT NULL DEFAULT '0',
    "balance_before_minor" bigint NOT NULL DEFAULT '0',
    "points" bigint NOT NULL DEFAULT '0',
    "balance_after_minor" bigint NOT NULL DEFAULT '0',
    "points_after" bigint NOT NULL DEFAULT '0',
    "description" varchar(255) DEFAULT NULL,
    "title_key" varchar(160) DEFAULT NULL,
    "message_key" varchar(160) DEFAULT NULL,
    "description_key" varchar(160) DEFAULT NULL,
    "counterparty_user_id" bigint DEFAULT NULL,
    "ref_type" varchar(80) DEFAULT NULL,
    "ref_id" bigint DEFAULT NULL,
    "legacy_source" varchar(80) DEFAULT NULL,
    "legacy_id" bigint DEFAULT NULL,
    "idempotency_key" varchar(190) DEFAULT NULL,
    "meta_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "previous_hash" varchar(128) DEFAULT NULL,
    "entry_hash" varchar(128) DEFAULT NULL,
    "hash_algorithm" varchar(20) DEFAULT 'hmac-sha256',
    "hash_version" integer DEFAULT '2',
    "signed_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_wallet_transactions_uq_wallet_tx_idempotency" UNIQUE ("idempotency_key")
);

CREATE TABLE "wallet_transfers" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "direction" varchar(32) NOT NULL,
    "status" varchar(32) NOT NULL,
    "source_wallet" varchar(32) NOT NULL,
    "target_wallet" varchar(32) NOT NULL,
    "source_amount" bigint NOT NULL,
    "target_amount" bigint NOT NULL,
    "fee_amount" bigint NOT NULL DEFAULT '0',
    "rate_numerator" bigint NOT NULL DEFAULT '1',
    "rate_denominator" bigint NOT NULL DEFAULT '1',
    "risk_score" integer NOT NULL DEFAULT '0',
    "reviewed_by" bigint DEFAULT NULL,
    "reviewed_at" timestamp without time zone DEFAULT NULL,
    "completed_at" timestamp without time zone DEFAULT NULL,
    "reason" varchar(255) DEFAULT NULL,
    "metadata_json" jsonb DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "wallets" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "main_available_minor" bigint NOT NULL DEFAULT '0',
    "main_reserved_minor" bigint NOT NULL DEFAULT '0',
    "slowo_available_minor" bigint NOT NULL DEFAULT '0',
    "slowo_reserved_minor" bigint NOT NULL DEFAULT '0',
    "available_minor" bigint NOT NULL DEFAULT '0',
    "pending_minor" bigint NOT NULL DEFAULT '0',
    "reserved_minor" bigint NOT NULL DEFAULT '0',
    "points_balance" bigint NOT NULL DEFAULT '0',
    "currency" char(3) NOT NULL DEFAULT 'PLN',
    "legacy_wallet_id" bigint DEFAULT NULL,
    "legacy_wallet_name" varchar(80) DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "updated_at" timestamp without time zone DEFAULT NULL,
    "is_locked" smallint NOT NULL DEFAULT '0',
    "locked_reason" varchar(255) DEFAULT NULL,
    "locked_at" timestamp without time zone DEFAULT NULL,
    "locked_by" bigint DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_wallets_user_id" UNIQUE ("user_id")
);

INSERT INTO "financial_ledger_head" (
    "id",
    "last_transaction_id",
    "last_entry_hash",
    "hash_version",
    "updated_at"
) VALUES (
    1,
    NULL,
    '0000000000000000000000000000000000000000000000000000000000000000',
    2,
    NOW()
);

CREATE INDEX "idx_activity_bonus_notifications_idx_abn_user_seen" ON "activity_bonus_notifications" ("user_id","seen_at","created_at");
CREATE INDEX "idx_activity_bonus_notifications_idx_slowo_bonus_notif_698bda5f" ON "activity_bonus_notifications" ("user_id","created_at");
CREATE INDEX "idx_activity_bonus_notifications_idx_bonus_notif_user__8411a9b0" ON "activity_bonus_notifications" ("user_id","activity_type","created_at");
CREATE INDEX "idx_activity_reward_logs_idx_arl_user_activity" ON "activity_reward_logs" ("user_id","activity_type");
CREATE INDEX "idx_activity_reward_logs_idx_arl_awarded_at" ON "activity_reward_logs" ("awarded_at");
CREATE INDEX "idx_activity_reward_logs_idx_arl_transaction" ON "activity_reward_logs" ("wallet_transaction_id");
CREATE INDEX "idx_activity_reward_logs_idx_slowo_activity_logs_user_awarded" ON "activity_reward_logs" ("user_id","awarded_at");
CREATE INDEX "idx_activity_reward_logs_idx_activity_reward_logs_user_28e9b0d7" ON "activity_reward_logs" ("user_id","awarded_at");
CREATE INDEX "idx_ad_clicks_idx_ad_clicks_campaign" ON "ad_clicks" ("campaign_id","clicked_at");
CREATE INDEX "idx_ad_clicks_fk_ad_clicks_user" ON "ad_clicks" ("user_id");
CREATE INDEX "idx_ad_clicks_fk_ad_clicks_event" ON "ad_clicks" ("campaign_event_id");
CREATE INDEX "idx_ad_views_idx_ad_views_campaign" ON "ad_views" ("campaign_id","viewed_at");
CREATE INDEX "idx_ad_views_fk_ad_views_event" ON "ad_views" ("campaign_event_id");
CREATE INDEX "idx_ad_views_idx_slowo_ad_views_user_viewed" ON "ad_views" ("user_id","viewed_at");
CREATE INDEX "idx_admin_audit_logs_idx_slowo_admin_audit_user_created" ON "admin_audit_logs" ("user_id","created_at");
CREATE INDEX "idx_ai_job_events_idx_ai_job_events_job" ON "ai_job_events" ("ai_job_id","created_at");
CREATE INDEX "idx_ai_job_events_idx_ai_job_events_type" ON "ai_job_events" ("event_type","created_at");
CREATE INDEX "idx_ai_job_events_idx_ai_job_events_actor" ON "ai_job_events" ("actor_user_id","created_at");
CREATE INDEX "idx_ai_jobs_idx_ai_jobs_article" ON "ai_jobs" ("article_id","created_at");
CREATE INDEX "idx_ai_jobs_idx_ai_jobs_status_type" ON "ai_jobs" ("status","type");
CREATE INDEX "idx_ai_jobs_idx_ai_jobs_provider" ON "ai_jobs" ("provider","model");
CREATE INDEX "idx_ai_jobs_idx_ai_jobs_user" ON "ai_jobs" ("user_id","created_at");
CREATE INDEX "idx_ai_jobs_idx_ai_jobs_budget" ON "ai_jobs" ("budget_period","budget_status");
CREATE INDEX "idx_ai_prompt_templates_idx_ai_prompt_task_active" ON "ai_prompt_templates" ("task_type","is_active");
CREATE INDEX "idx_article_access_grants_fk_aag_article" ON "article_access_grants" ("article_id");
CREATE INDEX "idx_article_access_grants_fk_aag_payment" ON "article_access_grants" ("payment_id");
CREATE INDEX "idx_article_access_grants_idx_slowo_article_access_user_article" ON "article_access_grants" ("user_id","article_id","status");
CREATE INDEX "idx_article_categories_fk_ac_category" ON "article_categories" ("category_id");
CREATE INDEX "idx_article_events_idx_article_events_article" ON "article_events" ("article_id");
CREATE INDEX "idx_article_events_fk_article_events_user" ON "article_events" ("user_id");
CREATE INDEX "idx_article_events_idx_article_events_proofread_lookup" ON "article_events" ("event","article_id","created_at");
CREATE INDEX "idx_article_purchases_idx_article_purchases_article" ON "article_purchases" ("article_id");
CREATE INDEX "idx_article_purchases_idx_article_purchases_author" ON "article_purchases" ("author_user_id");
CREATE INDEX "idx_article_purchases_fk_article_purchases_payment" ON "article_purchases" ("payment_id");
CREATE INDEX "idx_article_reads_idx_article_reads_article" ON "article_reads" ("article_id");
CREATE INDEX "idx_article_reads_idx_slowo_article_reads_user_created" ON "article_reads" ("user_id","created_at");
CREATE INDEX "idx_article_supports_idx_article_supports_article" ON "article_supports" ("article_id");
CREATE INDEX "idx_article_supports_fk_support_reader" ON "article_supports" ("reader_id");
CREATE INDEX "idx_article_supports_fk_support_author" ON "article_supports" ("author_id");
CREATE INDEX "idx_article_supports_fk_support_payment" ON "article_supports" ("payment_id");
CREATE INDEX "idx_article_translations_idx_article_translations_article" ON "article_translations" ("article_id","status");
CREATE INDEX "idx_article_translations_idx_article_translations_ai_job" ON "article_translations" ("ai_job_id");
CREATE INDEX "idx_article_translations_idx_article_translations_language" ON "article_translations" ("target_language","status");
CREATE INDEX "idx_article_translations_idx_article_translations_article_id" ON "article_translations" ("article_id");
CREATE INDEX "idx_article_translations_idx_article_translations_status" ON "article_translations" ("status");
CREATE INDEX "idx_article_translations_idx_article_translations_public_seo" ON "article_translations" ("status","language","slug","article_id");
CREATE INDEX "idx_article_translation_versions_idx_article_translati_31d9a83a" ON "article_translation_versions" ("translation_id","created_at");
CREATE INDEX "idx_article_translation_versions_fk_article_translatio_ecd308c5" ON "article_translation_versions" ("changed_by");
CREATE INDEX "idx_article_versions_fk_versions_article" ON "article_versions" ("article_id");
CREATE INDEX "idx_articles_idx_articles_status" ON "articles" ("status");
CREATE INDEX "idx_articles_idx_articles_legacy" ON "articles" ("legacy_source","legacy_id");
CREATE INDEX "idx_articles_idx_articles_pricing" ON "articles" ("access_mode","pricing_status","is_premium","is_unique");
CREATE INDEX "idx_articles_fk_articles_valued_by_admin" ON "articles" ("valued_by_admin_id");
CREATE INDEX "idx_articles_idx_slowo_articles_status_updated" ON "articles" ("status","updated_at");
CREATE INDEX "idx_articles_idx_slowo_articles_author_updated" ON "articles" ("author_id","updated_at");
CREATE INDEX "idx_articles_idx_slowo_articles_status_published" ON "articles" ("status","published_at");
CREATE INDEX "idx_articles_idx_articles_public_seo" ON "articles" ("status","slug","published_at","updated_at");
CREATE INDEX "idx_articles_idx_articles_revision" ON "articles" ("revision_of_article_id","status");
CREATE INDEX "idx_auth_login_events_idx_auth_login_user_created" ON "auth_login_events" ("user_id","created_at");
CREATE INDEX "idx_auth_login_events_idx_auth_login_result_created" ON "auth_login_events" ("result","created_at");
CREATE INDEX "idx_campaign_events_idx_campaign_events_campaign" ON "campaign_events" ("campaign_id","created_at");
CREATE INDEX "idx_campaign_events_idx_campaign_events_user" ON "campaign_events" ("user_id","created_at");
CREATE INDEX "idx_campaign_events_idx_slowo_campaign_events_user_created" ON "campaign_events" ("user_id","created_at");
CREATE INDEX "idx_campaign_events_idx_campaign_events_fraud" ON "campaign_events" ("fraud_status","fraud_risk_score","created_at");
CREATE INDEX "idx_campaign_events_idx_campaign_events_user_type_date_stage5" ON "campaign_events" ("user_id","event_type","event_date");
CREATE INDEX "idx_campaigns_idx_campaign_status_dates" ON "campaigns" ("status","starts_at","ends_at");
CREATE INDEX "idx_campaigns_idx_campaign_type" ON "campaigns" ("type");
CREATE INDEX "idx_campaigns_fk_campaign_admin" ON "campaigns" ("created_by_admin_id");
CREATE INDEX "idx_campaigns_idx_slowo_campaigns_status_created" ON "campaigns" ("status","created_at");
CREATE INDEX "idx_categories_idx_categories_legacy" ON "categories" ("legacy_source","legacy_id");
CREATE INDEX "idx_donations_fk_donation_payment" ON "donations" ("payment_id");
CREATE INDEX "idx_donations_fk_donation_campaign" ON "donations" ("campaign_id");
CREATE INDEX "idx_email_verification_tokens_idx_evt_user_created" ON "email_verification_tokens" ("user_id","created_at");
CREATE INDEX "idx_email_verification_tokens_idx_evt_token" ON "email_verification_tokens" ("token_hash");
CREATE INDEX "idx_finance_balance_reports_idx_balance_report_run" ON "finance_balance_reports" ("run_id");
CREATE INDEX "idx_finance_balance_reports_fk_balance_report_user" ON "finance_balance_reports" ("user_id");
CREATE INDEX "idx_finance_import_errors_fk_import_errors_run" ON "finance_import_errors" ("run_id");
CREATE INDEX "idx_finance_legacy_events_idx_legacy_event_ref" ON "finance_legacy_events" ("ref_transaction_id");
CREATE INDEX "idx_finance_legacy_events_fk_legacy_events_run" ON "finance_legacy_events" ("run_id");
CREATE INDEX "idx_finance_legacy_wallet_snapshots_idx_legacy_snapshot_user" ON "finance_legacy_wallet_snapshots" ("user_id");
CREATE INDEX "idx_finance_legacy_wallet_snapshots_fk_snapshot_run" ON "finance_legacy_wallet_snapshots" ("run_id");
CREATE INDEX "idx_financial_approvals_idx_fin_app_status" ON "financial_approvals" ("status");
CREATE INDEX "idx_financial_approvals_idx_fin_app_user" ON "financial_approvals" ("user_id");
CREATE INDEX "idx_financial_approvals_idx_fin_app_requested" ON "financial_approvals" ("requested_by");
CREATE INDEX "idx_financial_audit_log_idx_fin_audit_wallet" ON "financial_audit_log" ("wallet_id");
CREATE INDEX "idx_financial_audit_log_idx_fin_audit_action" ON "financial_audit_log" ("action");
CREATE INDEX "idx_fraud_events_idx_fraud_events_user_created" ON "fraud_events" ("user_id","created_at");
CREATE INDEX "idx_fraud_events_idx_fraud_events_score_created" ON "fraud_events" ("risk_score","created_at");
CREATE INDEX "idx_fraud_events_idx_fraud_events_status_created" ON "fraud_events" ("status","created_at");
CREATE INDEX "idx_fraud_events_idx_fraud_events_ref" ON "fraud_events" ("reference_type","reference_id");
CREATE INDEX "idx_live_events_fk_live_campaign" ON "live_events" ("campaign_id");
CREATE INDEX "idx_mail_queue_idx_mail_queue_claim" ON "mail_queue" ("status","available_at","id");
CREATE INDEX "idx_mail_queue_idx_mail_queue_lock" ON "mail_queue" ("locked_by","status");
CREATE INDEX "idx_mail_queue_fk_mail_user" ON "mail_queue" ("user_id");
CREATE INDEX "idx_background_jobs_claim" ON "background_jobs" ("queue_name","status","priority" DESC,"available_at","id");
CREATE INDEX "idx_background_jobs_lease" ON "background_jobs" ("status","lease_expires_at");
CREATE INDEX "idx_background_jobs_actor" ON "background_jobs" ("actor_user_id","created_at");
CREATE INDEX "idx_background_job_events_job" ON "background_job_events" ("background_job_id","created_at");
CREATE INDEX "idx_main_banner_translations_idx_main_banner_translati_00d7f857" ON "main_banner_translations" ("language");
CREATE INDEX "idx_main_banners_idx_main_banners_active" ON "main_banners" ("is_active");
CREATE INDEX "idx_media_idx_media_legacy" ON "media" ("legacy_source","legacy_id");
CREATE INDEX "idx_password_resets_fk_password_resets_user" ON "password_resets" ("user_id");
CREATE INDEX "idx_payment_events_fk_payment_events_payment" ON "payment_events" ("payment_id");
CREATE INDEX "idx_payment_gateway_events_idx_gateway_events_order" ON "payment_gateway_events" ("payment_order_id");
CREATE INDEX "idx_payment_gateway_events_idx_gateway_events_type_received" ON "payment_gateway_events" ("event_type","received_at");
CREATE INDEX "idx_payment_items_fk_payment_items_payment" ON "payment_items" ("payment_id");
CREATE INDEX "idx_payment_orders_idx_payment_orders_user_created" ON "payment_orders" ("user_id","created_at");
CREATE INDEX "idx_payment_orders_idx_payment_orders_provider_status" ON "payment_orders" ("provider","status");
CREATE INDEX "idx_payment_orders_idx_payment_orders_stripe_session" ON "payment_orders" ("stripe_session_id");
CREATE INDEX "idx_payment_orders_idx_payment_orders_stripe_pi" ON "payment_orders" ("stripe_payment_intent_id");
CREATE INDEX "idx_payment_orders_fk_payment_orders_topup_package" ON "payment_orders" ("topup_package_id");
CREATE INDEX "idx_payments_idx_payments_legacy" ON "payments" ("legacy_source","legacy_id");
CREATE INDEX "idx_payments_idx_payments_status" ON "payments" ("status");
CREATE INDEX "idx_payments_fk_payments_user" ON "payments" ("user_id");
CREATE INDEX "idx_payout_methods_fk_payout_method_user" ON "payout_methods" ("user_id");
CREATE INDEX "idx_payout_status_logs_idx_payout_status_logs_payout" ON "payout_status_logs" ("payout_id","created_at");
CREATE INDEX "idx_payout_status_logs_idx_payout_status_logs_user" ON "payout_status_logs" ("changed_by_user_id","created_at");
CREATE INDEX "idx_payouts_fk_payout_user" ON "payouts" ("user_id");
CREATE INDEX "idx_payouts_fk_payout_method" ON "payouts" ("payout_method_id");
CREATE INDEX "idx_payouts_idx_slowo_payouts_status_requested" ON "payouts" ("status","requested_at");
CREATE INDEX "idx_payouts_idx_payouts_fraud" ON "payouts" ("fraud_status","fraud_risk_score","requested_at");
CREATE INDEX "idx_platform_revenues_fk_pr_payment" ON "platform_revenues" ("payment_id");
CREATE INDEX "idx_platform_revenues_fk_pr_article" ON "platform_revenues" ("article_id");
CREATE INDEX "idx_platform_revenues_fk_pr_buyer" ON "platform_revenues" ("buyer_user_id");
CREATE INDEX "idx_platform_revenues_fk_pr_author" ON "platform_revenues" ("author_user_id");
CREATE INDEX "idx_ppv_events_fk_ppv_campaign" ON "ppv_events" ("campaign_id");
CREATE INDEX "idx_sessions_idx_sessions_user" ON "sessions" ("user_id");
CREATE INDEX "idx_sessions_idx_sessions_last_activity" ON "sessions" ("last_activity");
CREATE INDEX "idx_sponsored_article_reads_fk_sponsored_reads_campaign" ON "sponsored_article_reads" ("campaign_id");
CREATE INDEX "idx_sponsored_article_reads_fk_sponsored_reads_user" ON "sponsored_article_reads" ("user_id");
CREATE INDEX "idx_sponsored_article_reads_fk_sponsored_reads_event" ON "sponsored_article_reads" ("campaign_event_id");
CREATE INDEX "idx_sponsored_article_reads_fk_sponsored_reads_article" ON "sponsored_article_reads" ("article_id");
CREATE INDEX "idx_survey_questions_idx_survey_questions_survey" ON "survey_questions" ("survey_id","sort_order");
CREATE INDEX "idx_survey_reports_fk_survey_reports_survey" ON "survey_reports" ("survey_id");
CREATE INDEX "idx_survey_reports_fk_survey_reports_admin" ON "survey_reports" ("generated_by_admin_id");
CREATE INDEX "idx_survey_response_items_idx_survey_response_items_response" ON "survey_response_items" ("response_id");
CREATE INDEX "idx_survey_response_items_idx_survey_response_items_question" ON "survey_response_items" ("question_id");
CREATE INDEX "idx_survey_responses_idx_survey_responses_user" ON "survey_responses" ("user_id");
CREATE INDEX "idx_survey_responses_fk_survey_responses_wallet_tx" ON "survey_responses" ("wallet_transaction_id");
CREATE INDEX "idx_survey_responses_idx_slowo_survey_responses_survey_db8e25a8" ON "survey_responses" ("survey_id","completed_at");
CREATE INDEX "idx_survey_responses_idx_survey_responses_fraud" ON "survey_responses" ("fraud_status","fraud_risk_score","created_at");
CREATE INDEX "idx_survey_responses_idx_survey_responses_user_created_stage5" ON "survey_responses" ("user_id","created_at");
CREATE INDEX "idx_surveys_idx_surveys_status_dates" ON "surveys" ("status","starts_at","ends_at");
CREATE INDEX "idx_surveys_idx_surveys_type" ON "surveys" ("type");
CREATE INDEX "idx_surveys_fk_surveys_admin" ON "surveys" ("created_by_admin_id");
CREATE INDEX "idx_surveys_idx_slowo_surveys_status_updated" ON "surveys" ("status","updated_at");
CREATE INDEX "idx_user_activity_events_idx_user_activity_events_user" ON "user_activity_events" ("user_id","created_at");
CREATE INDEX "idx_user_activity_events_idx_user_activity_events_type" ON "user_activity_events" ("activity_type","created_at");
CREATE INDEX "idx_user_delete_reports_idx_user_delete_reports_user" ON "user_delete_reports" ("deleted_user_id","created_at");
CREATE INDEX "idx_user_delete_reports_idx_user_delete_reports_admin" ON "user_delete_reports" ("deleted_by_admin_id","created_at");
CREATE INDEX "idx_user_oauth_accounts_user_id" ON "user_oauth_accounts" ("user_id");
CREATE INDEX "idx_user_oauth_accounts_provider_email" ON "user_oauth_accounts" ("provider_email");
CREATE INDEX "idx_user_profiles_fk_profiles_user" ON "user_profiles" ("user_id");
CREATE INDEX "idx_user_roles_idx_slowo_user_roles_user_role" ON "user_roles" ("user_id","role");
CREATE INDEX "idx_user_roles_idx_slowo_user_roles_role_user" ON "user_roles" ("role","user_id");
CREATE INDEX "idx_user_roles_idx_slowo_user_roles_role_user_stage4" ON "user_roles" ("role","user_id");
CREATE INDEX "idx_users_idx_users_legacy" ON "users" ("legacy_source","legacy_id");
CREATE UNIQUE INDEX "uq_users_login_name" ON "users" (LOWER("login_name")) WHERE "login_name" IS NOT NULL;
CREATE INDEX "idx_users_idx_users_deletion" ON "users" ("status","deleted_at","deletion_mode");
CREATE INDEX "idx_users_fk_users_deleted_by_admin" ON "users" ("deleted_by_admin_id");
CREATE INDEX "idx_users_idx_slowo_users_status_created" ON "users" ("status","created_at");
CREATE INDEX "idx_users_idx_users_email_verified" ON "users" ("email_verified_at");
CREATE INDEX "idx_users_idx_users_two_factor_enabled" ON "users" ("two_factor_enabled");
CREATE INDEX "idx_users_idx_users_auth_security_level" ON "users" ("auth_security_level");
CREATE INDEX "idx_users_idx_users_article_submit_blocked_until" ON "users" ("article_submit_blocked_until");
CREATE INDEX "idx_wallet_price_packages_idx_wallet_packages_legacy" ON "wallet_price_packages" ("legacy_source","legacy_id");
CREATE INDEX "idx_wallet_topup_packages_idx_wallet_topup_packages_active_sort" ON "wallet_topup_packages" ("is_active","sort_order");
CREATE INDEX "idx_wallet_transactions_idx_wallet_tx_user" ON "wallet_transactions" ("user_id");
CREATE INDEX "idx_wallet_transactions_idx_wallet_tx_legacy" ON "wallet_transactions" ("legacy_source","legacy_id");
CREATE INDEX "idx_wallet_transactions_fk_tx_wallet" ON "wallet_transactions" ("wallet_id");
CREATE INDEX "idx_wallet_transactions_fk_tx_counterparty" ON "wallet_transactions" ("counterparty_user_id");
CREATE INDEX "idx_wallet_transactions_idx_slowo_wallet_tx_user_created" ON "wallet_transactions" ("user_id","created_at");
CREATE INDEX "idx_wallet_transactions_idx_slowo_wallet_tx_user_type_created" ON "wallet_transactions" ("user_id","type","created_at");
CREATE INDEX "idx_wallet_transactions_idx_wallet_tx_user_type_created_keys" ON "wallet_transactions" ("user_id","type","created_at");
CREATE INDEX "idx_wallet_transfers_idx_wallet_transfers_user_created" ON "wallet_transfers" ("user_id","created_at");
CREATE INDEX "idx_wallet_transfers_idx_wallet_transfers_status_created" ON "wallet_transfers" ("status","created_at");
CREATE INDEX "idx_wallet_transfers_idx_wallet_transfers_direction" ON "wallet_transfers" ("direction");
CREATE INDEX "idx_wallet_transfers_fk_wallet_transfers_reviewed_by" ON "wallet_transfers" ("reviewed_by");
CREATE INDEX "idx_wallets_idx_wallet_legacy" ON "wallets" ("legacy_wallet_id");

ALTER TABLE "activity_bonus_notifications" ADD CONSTRAINT "fk_abn_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "activity_reward_logs" ADD CONSTRAINT "fk_arl_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "activity_reward_logs" ADD CONSTRAINT "fk_arl_wallet_transaction" FOREIGN KEY ("wallet_transaction_id") REFERENCES "wallet_transactions" ("id") ON DELETE SET NULL;
ALTER TABLE "ad_clicks" ADD CONSTRAINT "fk_ad_clicks_campaign" FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id") ON DELETE CASCADE;
ALTER TABLE "ad_clicks" ADD CONSTRAINT "fk_ad_clicks_event" FOREIGN KEY ("campaign_event_id") REFERENCES "campaign_events" ("id") ON DELETE CASCADE;
ALTER TABLE "ad_clicks" ADD CONSTRAINT "fk_ad_clicks_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "ad_views" ADD CONSTRAINT "fk_ad_views_campaign" FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id") ON DELETE CASCADE;
ALTER TABLE "ad_views" ADD CONSTRAINT "fk_ad_views_event" FOREIGN KEY ("campaign_event_id") REFERENCES "campaign_events" ("id") ON DELETE CASCADE;
ALTER TABLE "ad_views" ADD CONSTRAINT "fk_ad_views_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "article_access_grants" ADD CONSTRAINT "fk_aag_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "article_access_grants" ADD CONSTRAINT "fk_aag_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE SET NULL;
ALTER TABLE "article_access_grants" ADD CONSTRAINT "fk_aag_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "article_categories" ADD CONSTRAINT "fk_ac_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "article_categories" ADD CONSTRAINT "fk_ac_category" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE;
ALTER TABLE "article_events" ADD CONSTRAINT "fk_article_events_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "article_events" ADD CONSTRAINT "fk_article_events_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "article_purchases" ADD CONSTRAINT "fk_article_purchases_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "article_purchases" ADD CONSTRAINT "fk_article_purchases_author" FOREIGN KEY ("author_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "article_purchases" ADD CONSTRAINT "fk_article_purchases_buyer" FOREIGN KEY ("buyer_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "article_purchases" ADD CONSTRAINT "fk_article_purchases_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE SET NULL;
ALTER TABLE "article_reads" ADD CONSTRAINT "fk_article_reads_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "article_reads" ADD CONSTRAINT "fk_article_reads_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "article_supports" ADD CONSTRAINT "fk_support_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "article_supports" ADD CONSTRAINT "fk_support_author" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "article_supports" ADD CONSTRAINT "fk_support_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE CASCADE;
ALTER TABLE "article_supports" ADD CONSTRAINT "fk_support_reader" FOREIGN KEY ("reader_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "article_translation_versions" ADD CONSTRAINT "fk_article_translation_versions_translation" FOREIGN KEY ("translation_id") REFERENCES "article_translations" ("id") ON DELETE CASCADE;
ALTER TABLE "article_translation_versions" ADD CONSTRAINT "fk_article_translation_versions_user" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "article_versions" ADD CONSTRAINT "fk_versions_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "articles" ADD CONSTRAINT "fk_articles_author" FOREIGN KEY ("author_id") REFERENCES "users" ("id");
ALTER TABLE "articles" ADD CONSTRAINT "fk_articles_revision" FOREIGN KEY ("revision_of_article_id") REFERENCES "articles" ("id") ON DELETE SET NULL;
ALTER TABLE "articles" ADD CONSTRAINT "fk_articles_valued_by_admin" FOREIGN KEY ("valued_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "campaign_events" ADD CONSTRAINT "fk_campaign_events_campaign" FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id") ON DELETE CASCADE;
ALTER TABLE "campaign_events" ADD CONSTRAINT "fk_campaign_events_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "campaigns" ADD CONSTRAINT "fk_campaign_admin" FOREIGN KEY ("created_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "category_translations" ADD CONSTRAINT "fk_ct_category" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE;
ALTER TABLE "donations" ADD CONSTRAINT "fk_donation_campaign" FOREIGN KEY ("campaign_id") REFERENCES "donation_campaigns" ("id") ON DELETE SET NULL;
ALTER TABLE "donations" ADD CONSTRAINT "fk_donation_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE CASCADE;
ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "fk_evt_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "finance_balance_reports" ADD CONSTRAINT "fk_balance_report_run" FOREIGN KEY ("run_id") REFERENCES "finance_import_runs" ("id") ON DELETE SET NULL;
ALTER TABLE "finance_balance_reports" ADD CONSTRAINT "fk_balance_report_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "finance_import_errors" ADD CONSTRAINT "fk_import_errors_run" FOREIGN KEY ("run_id") REFERENCES "finance_import_runs" ("id") ON DELETE CASCADE;
ALTER TABLE "finance_legacy_events" ADD CONSTRAINT "fk_legacy_events_run" FOREIGN KEY ("run_id") REFERENCES "finance_import_runs" ("id") ON DELETE SET NULL;
ALTER TABLE "finance_legacy_wallet_snapshots" ADD CONSTRAINT "fk_snapshot_run" FOREIGN KEY ("run_id") REFERENCES "finance_import_runs" ("id") ON DELETE SET NULL;
ALTER TABLE "finance_legacy_wallet_snapshots" ADD CONSTRAINT "fk_snapshot_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "fraud_events" ADD CONSTRAINT "fk_fraud_events_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "live_events" ADD CONSTRAINT "fk_live_campaign" FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id") ON DELETE SET NULL;
ALTER TABLE "mail_queue" ADD CONSTRAINT "fk_mail_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "background_jobs" ADD CONSTRAINT "fk_background_jobs_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "background_job_events" ADD CONSTRAINT "fk_background_job_events_job" FOREIGN KEY ("background_job_id") REFERENCES "background_jobs" ("id") ON DELETE CASCADE;
ALTER TABLE "main_banner_translations" ADD CONSTRAINT "fk_main_banner_translations_banner" FOREIGN KEY ("banner_id") REFERENCES "main_banners" ("id") ON DELETE CASCADE;
ALTER TABLE "password_resets" ADD CONSTRAINT "fk_password_resets_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "payment_events" ADD CONSTRAINT "fk_payment_events_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE CASCADE;
ALTER TABLE "payment_gateway_events" ADD CONSTRAINT "fk_gateway_events_order" FOREIGN KEY ("payment_order_id") REFERENCES "payment_orders" ("id") ON DELETE SET NULL;
ALTER TABLE "payment_items" ADD CONSTRAINT "fk_payment_items_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE CASCADE;
ALTER TABLE "payment_orders" ADD CONSTRAINT "fk_payment_orders_topup_package" FOREIGN KEY ("topup_package_id") REFERENCES "wallet_topup_packages" ("id") ON DELETE SET NULL;
ALTER TABLE "payment_orders" ADD CONSTRAINT "fk_payment_orders_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "payout_methods" ADD CONSTRAINT "fk_payout_method_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "payout_status_logs" ADD CONSTRAINT "fk_payout_status_logs_payout" FOREIGN KEY ("payout_id") REFERENCES "payouts" ("id") ON DELETE CASCADE;
ALTER TABLE "payout_status_logs" ADD CONSTRAINT "fk_payout_status_logs_user" FOREIGN KEY ("changed_by_user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "payouts" ADD CONSTRAINT "fk_payout_method" FOREIGN KEY ("payout_method_id") REFERENCES "payout_methods" ("id") ON DELETE SET NULL;
ALTER TABLE "payouts" ADD CONSTRAINT "fk_payout_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "platform_revenues" ADD CONSTRAINT "fk_pr_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE SET NULL;
ALTER TABLE "platform_revenues" ADD CONSTRAINT "fk_pr_author" FOREIGN KEY ("author_user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "platform_revenues" ADD CONSTRAINT "fk_pr_buyer" FOREIGN KEY ("buyer_user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "platform_revenues" ADD CONSTRAINT "fk_pr_payment" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE SET NULL;
ALTER TABLE "ppv_events" ADD CONSTRAINT "fk_ppv_campaign" FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id") ON DELETE SET NULL;
ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "sponsored_article_reads" ADD CONSTRAINT "fk_sponsored_reads_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE SET NULL;
ALTER TABLE "sponsored_article_reads" ADD CONSTRAINT "fk_sponsored_reads_campaign" FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id") ON DELETE CASCADE;
ALTER TABLE "sponsored_article_reads" ADD CONSTRAINT "fk_sponsored_reads_event" FOREIGN KEY ("campaign_event_id") REFERENCES "campaign_events" ("id") ON DELETE CASCADE;
ALTER TABLE "sponsored_article_reads" ADD CONSTRAINT "fk_sponsored_reads_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "survey_questions" ADD CONSTRAINT "fk_survey_questions_survey" FOREIGN KEY ("survey_id") REFERENCES "surveys" ("id") ON DELETE CASCADE;
ALTER TABLE "survey_reports" ADD CONSTRAINT "fk_survey_reports_admin" FOREIGN KEY ("generated_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "survey_reports" ADD CONSTRAINT "fk_survey_reports_survey" FOREIGN KEY ("survey_id") REFERENCES "surveys" ("id") ON DELETE CASCADE;
ALTER TABLE "survey_response_items" ADD CONSTRAINT "fk_survey_response_items_question" FOREIGN KEY ("question_id") REFERENCES "survey_questions" ("id") ON DELETE CASCADE;
ALTER TABLE "survey_response_items" ADD CONSTRAINT "fk_survey_response_items_response" FOREIGN KEY ("response_id") REFERENCES "survey_responses" ("id") ON DELETE CASCADE;
ALTER TABLE "survey_responses" ADD CONSTRAINT "fk_survey_responses_survey" FOREIGN KEY ("survey_id") REFERENCES "surveys" ("id") ON DELETE CASCADE;
ALTER TABLE "survey_responses" ADD CONSTRAINT "fk_survey_responses_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "survey_responses" ADD CONSTRAINT "fk_survey_responses_wallet_tx" FOREIGN KEY ("wallet_transaction_id") REFERENCES "wallet_transactions" ("id") ON DELETE SET NULL;
ALTER TABLE "surveys" ADD CONSTRAINT "fk_surveys_admin" FOREIGN KEY ("created_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "user_activity_events" ADD CONSTRAINT "fk_user_activity_events_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_delete_reports" ADD CONSTRAINT "fk_user_delete_reports_admin" FOREIGN KEY ("deleted_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "user_oauth_accounts" ADD CONSTRAINT "user_oauth_accounts_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_profiles" ADD CONSTRAINT "fk_profiles_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_roles" ADD CONSTRAINT "fk_roles_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "users" ADD CONSTRAINT "fk_users_deleted_by_admin" FOREIGN KEY ("deleted_by_admin_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "wallet_transactions" ADD CONSTRAINT "fk_tx_counterparty" FOREIGN KEY ("counterparty_user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "wallet_transactions" ADD CONSTRAINT "fk_tx_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "wallet_transactions" ADD CONSTRAINT "fk_tx_wallet" FOREIGN KEY ("wallet_id") REFERENCES "wallets" ("id") ON DELETE CASCADE;
ALTER TABLE "wallet_transfers" ADD CONSTRAINT "fk_wallet_transfers_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "wallet_transfers" ADD CONSTRAINT "fk_wallet_transfers_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "wallets" ADD CONSTRAINT "fk_wallet_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

-- ETAP 7: nowa instalacja startuje od pustej, zweryfikowanej księgi per-portfel.
ALTER TABLE "wallet_transactions"
    ADD COLUMN "wallet_previous_hash" char(64) NULL,
    ADD COLUMN "wallet_entry_hash" char(64) NULL,
    ADD COLUMN "wallet_hash_algorithm" varchar(20) NULL,
    ADD COLUMN "wallet_hash_version" integer NULL,
    ADD COLUMN "wallet_signed_at" timestamp without time zone NULL;
CREATE INDEX "idx_wallet_transactions_wallet_chain" ON "wallet_transactions" ("wallet_id","id");

CREATE TABLE "financial_ledger_migration_state" (
    "id" smallint PRIMARY KEY,
    "mode" varchar(24) NOT NULL CHECK ("mode" IN ('legacy_global','per_wallet')),
    "legacy_cutover_transaction_id" bigint NULL,
    "compliance_report_json" jsonb NULL,
    "compliance_report_hash" char(64) NULL,
    "verified_at" timestamp without time zone NULL,
    "activated_at" timestamp without time zone NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "financial_ledger_migration_state" ("id","mode","compliance_report_json","compliance_report_hash","verified_at","activated_at","updated_at")
VALUES (1,'per_wallet','{"legacy_transactions":0,"wallet_transactions":0,"wallets":0,"errors":[]}','81419e7755b60b2dc579724ef82203118ea3fa5569380637bcef247a5028c414',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

CREATE TABLE "financial_wallet_ledger_heads" (
    "wallet_id" bigint PRIMARY KEY REFERENCES "wallets" ("id") ON DELETE CASCADE,
    "last_transaction_id" bigint NULL REFERENCES "wallet_transactions" ("id") ON DELETE RESTRICT,
    "last_entry_hash" char(64) NOT NULL,
    "transaction_count" bigint NOT NULL DEFAULT 0 CHECK ("transaction_count" >= 0),
    "hash_version" integer NOT NULL DEFAULT 2,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "financial_operations" (
    "idempotency_key" varchar(190) PRIMARY KEY,
    "request_hash" char(64) NOT NULL,
    "status" varchar(16) NOT NULL CHECK ("status" IN ('processing','completed')),
    "wallet_id" bigint NULL REFERENCES "wallets" ("id") ON DELETE RESTRICT,
    "transaction_id" bigint NULL UNIQUE REFERENCES "wallet_transactions" ("id") ON DELETE RESTRICT,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" timestamp without time zone NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "financial_ledger_anchors" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "period_start" timestamp without time zone NOT NULL,
    "period_end" timestamp without time zone NOT NULL,
    "cutoff_transaction_id" bigint NULL,
    "wallet_count" integer NOT NULL DEFAULT 0 CHECK ("wallet_count" >= 0),
    "transaction_count" bigint NOT NULL DEFAULT 0 CHECK ("transaction_count" >= 0),
    "merkle_root" char(64) NOT NULL,
    "previous_anchor_hash" char(64) NOT NULL,
    "anchor_hash" char(64) NOT NULL,
    "hash_algorithm" varchar(20) NOT NULL DEFAULT 'hmac-sha256',
    "hash_version" integer NOT NULL DEFAULT 2,
    "manifest_json" jsonb NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uq_financial_ledger_anchors_period" UNIQUE ("period_start","period_end")
);
CREATE INDEX "idx_financial_ledger_anchors_created" ON "financial_ledger_anchors" ("created_at","id");

CREATE OR REPLACE FUNCTION enforce_nonnegative_wallet_balances()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.main_available_minor < 0 THEN
        RAISE EXCEPTION 'Błąd: saldo główne nie może być ujemne.';
    END IF;
    IF NEW.slowo_available_minor < 0 THEN
        RAISE EXCEPTION 'Błąd: saldo SŁOWO nie może być ujemne.';
    END IF;
    IF NEW.main_reserved_minor < 0
       OR NEW.slowo_reserved_minor < 0
       OR NEW.reserved_minor < 0 THEN
        RAISE EXCEPTION 'Błąd: saldo zarezerwowane nie może być ujemne.';
    END IF;
    IF NEW.points_balance < 0 THEN
        RAISE EXCEPTION 'Błąd: saldo Talentów nie może być ujemne.';
    END IF;
    RETURN NEW;
END
$function$;

CREATE TRIGGER trg_wallets_before_update
BEFORE UPDATE ON "wallets"
FOR EACH ROW
EXECUTE FUNCTION enforce_nonnegative_wallet_balances();

-- Selektywne przywracanie treści i administratora: jawny ślad przebiegu oraz
-- niezmienne archiwum starego, globalnego łańcucha finansowego.
CREATE TABLE "selected_migration_runs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(64) NOT NULL UNIQUE,
    "mode" varchar(16) NOT NULL CHECK ("mode" IN ('dry-run','apply','resume')),
    "source_database" varchar(190) NOT NULL,
    "source_admin_id" bigint NOT NULL,
    "source_manifest_hash" char(64) NOT NULL,
    "financial_approval" varchar(255) NOT NULL,
    "status" varchar(20) NOT NULL CHECK ("status" IN ('running','completed','failed')),
    "report_json" jsonb NULL,
    "started_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" timestamp without time zone NULL
);
CREATE INDEX "idx_selected_migration_runs_status" ON "selected_migration_runs" ("status","started_at");

CREATE TABLE "selected_migration_legacy_wallet_transactions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "run_id" bigint NOT NULL REFERENCES "selected_migration_runs" ("id") ON DELETE RESTRICT,
    "source_transaction_id" bigint NOT NULL,
    "source_wallet_id" bigint NOT NULL,
    "source_user_id" bigint NOT NULL,
    "original_previous_hash" varchar(128) NULL,
    "original_entry_hash" varchar(128) NULL,
    "original_hash_algorithm" varchar(20) NULL,
    "original_hash_version" integer NULL,
    "source_row_json" jsonb NOT NULL,
    "source_row_checksum" char(64) NOT NULL,
    "archived_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "uq_selected_legacy_wallet_transaction" UNIQUE ("run_id","source_transaction_id")
);
CREATE INDEX "idx_selected_legacy_wallet_transactions_source"
    ON "selected_migration_legacy_wallet_transactions" ("source_user_id","source_wallet_id","source_transaction_id");

CREATE TABLE "selected_migration_article_authors" (
    "run_id" bigint NOT NULL REFERENCES "selected_migration_runs" ("id") ON DELETE RESTRICT,
    "source_article_id" bigint NOT NULL,
    "original_author_id" bigint NOT NULL,
    "target_admin_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("run_id","source_article_id")
);

CREATE OR REPLACE FUNCTION protect_selected_migration_archive()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'Archiwum selektywnej migracji jest niezmienne.';
END
$function$;

CREATE TRIGGER "trg_protect_selected_migration_legacy_wallet_transactions"
BEFORE UPDATE OR DELETE ON "selected_migration_legacy_wallet_transactions"
FOR EACH ROW EXECUTE FUNCTION protect_selected_migration_archive();
CREATE TRIGGER "trg_protect_selected_migration_article_authors"
BEFORE UPDATE OR DELETE ON "selected_migration_article_authors"
FOR EACH ROW EXECUTE FUNCTION protect_selected_migration_archive();

COMMIT;
