<section class="admin-panel-block zs-bug-review-panel">
  <div class="admin-section-head"><div><p class="kicker">Zgłoszenia od użytkowników</p><h2>Prawdziwy błąd nagradzamy po akceptacji</h2><p>Samo wysłanie i odrzucenie nie przyznaje TT. Jedno zaakceptowane zgłoszenie może uruchomić nagrodę tylko raz.</p></div><span><?= count($bug_reports) ?> zgłoszeń</span></div>
  <?php if($bug_reports===[]):?><div class="empty-state"><h3>Brak zgłoszeń</h3><p>Nowe pozycje z formularza „Zgłoś błąd” pojawią się tutaj.</p></div><?php else:?><div class="zs-bug-review-list">
  <?php foreach($bug_reports as $report):?><article class="is-<?= e((string)$report['status']) ?>">
    <header><div><strong><?= e((string)($report['user_name']?:$report['user_email']?:'Zgłoszenie anonimowe')) ?></strong><small><?= e((string)$report['created_at']) ?> · <?= e((string)$report['page_url']) ?></small></div><span><?= match((string)$report['status']){'accepted'=>'Zaakceptowane','rejected'=>'Odrzucone',default=>'Do sprawdzenia'} ?></span></header>
    <p><?= nl2br(e((string)$report['description'])) ?></p><?php if(!empty($report['details'])):?><details><summary>Dodatkowe informacje</summary><p><?= nl2br(e((string)$report['details'])) ?></p></details><?php endif;?>
    <?php if(!empty($report['attachment_path'])):?><a href="<?= e((string)$report['attachment_path']) ?>" target="_blank"><img src="<?= e((string)$report['attachment_path']) ?>" alt="Załącznik zgłoszenia"></a><?php endif;?>
    <?php if((string)$report['status']==='submitted'):?><form method="post" action="/admin/bug-reports/review" class="zs-bug-decision-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$report['id'] ?>"><input type="hidden" name="return_to" value="<?= e((string)($bug_report_return_to ?? 'campaigns')) ?>"><label class="field"><span>Notatka decyzji</span><input name="note" placeholder="Krótko opisz wynik sprawdzenia"></label><button class="btn-red" name="decision" value="accept">Zaakceptuj i przyznaj TT</button><button class="btn-line" name="decision" value="reject">Odrzuć bez TT</button></form><?php else:?><div class="zs-human-note"><strong><?= (int)($report['reward_points']??0) ?> TT</strong><p><?= e((string)($report['review_note']??'Bez dodatkowej notatki')) ?></p></div><?php endif;?>
  </article><?php endforeach;?></div><?php endif;?>
</section>
