<section class="admin-panel-block zs-bug-review-panel">
  <div class="admin-section-head"><div><p class="kicker"><?= e(t('admin.partials.bug_reports.zgoszenia_od_uzytkownikow')) ?></p><h2><?= e(t('admin.partials.bug_reports.prawdziwy_bad_nagradzamy_po_akceptacji')) ?></h2><p><?= e(t('admin.partials.bug_reports.samo_wysanie_i_odrzucenie_nie_przyznaje_tt_jedno_zaakce_b41be592')) ?></p></div><span><?= e(str_replace('{count}', (string)count($bug_reports), t('admin.bug_reports.reports_count'))) ?></span></div>
  <?php if($bug_reports===[]):?><div class="empty-state"><h3><?= e(t('admin.partials.bug_reports.brak_zgoszen')) ?></h3><p><?= e(t('admin.partials.bug_reports.nowe_pozycje_z_formularza_zgos_bad_pojawia_sie_tutaj')) ?></p></div><?php else:?><div class="zs-bug-review-list">
  <?php foreach($bug_reports as $report):?><article class="is-<?= e((string)$report['status']) ?>">
    <header><div><strong><?= e((string)($report['user_name']?:$report['user_email']?:t('admin.partials.bug_reports.zgoszenie_anonimowe'))) ?></strong><small><?= e((string)$report['created_at']) ?> · <?= e((string)$report['page_url']) ?></small></div><span><?= e(match((string)$report['status']){'accepted'=>t('admin.bug_reports.status_accepted'),'rejected'=>t('admin.bug_reports.status_rejected'),default=>t('admin.bug_reports.status_review')}) ?></span></header>
    <p><?= nl2br(e((string)$report['description'])) ?></p><?php if(!empty($report['details'])):?><details><summary><?= e(t('admin.partials.bug_reports.dodatkowe_informacje')) ?></summary><p><?= nl2br(e((string)$report['details'])) ?></p></details><?php endif;?>
    <?php if(!empty($report['attachment_path'])):?><a href="<?= e((string)$report['attachment_path']) ?>" target="_blank"><img src="<?= e((string)$report['attachment_path']) ?>" alt="<?= e(t('admin.partials.bug_reports.zaacznik_zgoszenia')) ?>"></a><?php endif;?>
<?php if((string)$report['status']==='submitted'):?><form method="post" action="/admin/bug-reports/review" class="zs-bug-decision-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$report['id'] ?>"><input type="hidden" name="return_to" value="<?= e((string)($bug_report_return_to ?? 'campaigns')) ?>"><label class="field"><span><?= e(t('admin.partials.bug_reports.notatka_decyzji')) ?></span><input name="note" placeholder="<?= e(t('admin.partials.bug_reports.krotko_opisz_wynik_sprawdzenia')) ?>"></label><button class="btn-red" name="decision" value="accept"><?= e(t('admin.partials.bug_reports.zaakceptuj_i_przyznaj_tt')) ?></button><button class="btn-line" name="decision" value="reject"><?= e(t('admin.partials.bug_reports.odrzuc_bez_tt')) ?></button></form><?php else:?><div class="zs-human-note"><strong><?= (int)($report['reward_points']??0) ?> TT</strong><p><?= e((string)($report['review_note']??t('admin.partials.bug_reports.no_additional_note'))) ?></p></div><?php endif;?>
  </article><?php endforeach;?></div><?php endif;?>
</section>
