<?php
$surveyEdit = is_array($selected_survey ?? null) ? $selected_survey : [];
$surveyStatuses = ['draft'=>t('article.status.draft'),'active'=>t('admin.surveys.status_active'),'paused'=>t('admin.surveys.status_paused'),'closed'=>t('admin.partials.campaign_form.zakonczona')];
$surveyTypeLabels = ['consumer'=>t('survey.type.consumer'),'political_poll'=>t('admin.partials.campaign_surveys.sondaz_polityczny'),'social_poll'=>t('survey.type.social_poll'),'local_poll'=>t('survey.type.local_poll'),'advertising'=>t('survey.type.advertising'),'editorial'=>t('survey.type.editorial'),'market_research'=>t('survey.type.market_research')];
$questionTypeLabels = ['single_choice'=>t('admin.partials.campaign_surveys.jedna_odpowiedz'),'multiple_choice'=>t('admin.partials.campaign_surveys.multiple_choice'),'text'=>t('admin.partials.campaign_surveys.odpowiedz_tekstowa')];
?>
<section class="admin-panel-block zs-survey-workbench" id="ankiety">
  <div class="admin-section-head"><div><p class="kicker"><?= e(t('admin.partials.campaign_surveys.tresc_ankiety')) ?></p><h2><?= $surveyEdit ? t('admin.partials.campaign_surveys.edytuj_ankiete') : t('admin.partials.campaign_surveys.utworz_ankiete') ?></h2><p><?= e(t('admin.partials.campaign_surveys.najpierw_przygotuj_ankiete_i_pytania_nastepnie_przypnij_017da682')) ?></p></div><?php if($surveyEdit):?><a class="btn-line compact" href="/admin/campaigns?tab=survey#ankiety"><?= e(t('admin.partials.campaign_surveys.nowa_ankieta')) ?></a><?php endif;?></div>
  <aside class="zs-human-note"><strong><?= e(t('admin.partials.campaign_surveys.jedno_proste_rozliczenie')) ?></strong><p><?= e(t('admin.partials.campaign_surveys.budzet_i_stawke_pln_ustawiasz_w_kampanii_przypietej_do_50d0a911')) ?></p></aside>
  <form method="post" action="<?= $surveyEdit ? '/admin/surveys/update' : '/admin/surveys' ?>" class="form-grid two">
    <?= csrf_field() ?><?php if($surveyEdit):?><input type="hidden" name="id" value="<?= (int)$surveyEdit['id'] ?>"><?php endif;?>
    <label class="field"><span><?= e(t('author.article.title')) ?></span><input name="title" required value="<?= e((string)($surveyEdit['title']??'')) ?>"></label>
    <label class="field"><span><?= e(t('admin.partials.campaign_surveys.rodzaj')) ?></span><select name="type"><?php foreach($survey_types as $type):?><option value="<?= e($type) ?>" <?= ($surveyEdit['type']??'editorial')===$type?'selected':'' ?>><?= e($surveyTypeLabels[$type]??$type) ?></option><?php endforeach;?></select></label>
    <label class="field"><span><?= e(t('admin.partials.campaign_form.zleceniodawca')) ?></span><input name="client_name" value="<?= e((string)($surveyEdit['client_name']??'')) ?>"></label>
    <label class="field"><span><?= e(t('admin.partials.campaign_surveys.stan_ankiety')) ?></span><select name="status"><?php foreach($surveyStatuses as $key=>$label):?><option value="<?= e($key) ?>" <?= ($surveyEdit['status']??'draft')===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach;?></select></label>
    <input type="hidden" name="budget" value="0"><input type="hidden" name="reward_amount" value="0">
    <label class="field"><span><?= e(t('admin.partials.campaign_surveys.limit_odpowiedzi')) ?></span><input type="number" min="0" name="max_responses" value="<?= (int)($surveyEdit['max_responses']??0) ?>"><small><?= e(t('admin.partials.campaign_surveys.0_oznacza_brak_limitu_liczbowego')) ?></small></label>
    <label class="field full"><span><?= e(t('admin.partials.campaign_surveys.opis')) ?></span><textarea name="description" rows="3"><?= e((string)($surveyEdit['description']??'')) ?></textarea></label>
    <label class="field"><span><?= e(t('admin.partials.campaign_form.start')) ?></span><input type="datetime-local" name="starts_at" value="<?= e(!empty($surveyEdit['starts_at'])?str_replace(' ','T',substr((string)$surveyEdit['starts_at'],0,16)):'') ?>"></label>
    <label class="field"><span><?= e(t('admin.partials.campaign_form.koniec')) ?></span><input type="datetime-local" name="ends_at" value="<?= e(!empty($surveyEdit['ends_at'])?str_replace(' ','T',substr((string)$surveyEdit['ends_at'],0,16)):'') ?>"></label>
    <div class="full"><button class="btn-red" type="submit"><?= $surveyEdit?t('admin.partials.campaign_surveys.zapisz_ankiete'):t('admin.partials.campaign_surveys.utworz_ankiete') ?></button></div>
  </form>

  <?php if($surveyEdit):?>
    <details class="zs-human-details" open><summary><span>+</span><strong><?= e(t('admin.partials.campaign_surveys.pytania_ankiety')) ?></strong></summary>
      <form method="post" action="/admin/surveys/questions" class="form-grid two">
        <?= csrf_field() ?><input type="hidden" name="survey_id" value="<?= (int)$surveyEdit['id'] ?>">
        <label class="field full"><span><?= e(t('admin.partials.campaign_surveys.tresc_pytania')) ?></span><input name="question_text" required></label>
        <label class="field"><span><?= e(t('admin.partials.campaign_surveys.rodzaj_odpowiedzi')) ?></span><select name="question_type"><option value="single_choice"><?= e(t('admin.partials.campaign_surveys.jedna_odpowiedz')) ?></option><option value="multiple_choice"><?= e(t('admin.partials.campaign_surveys.wiele_odpowiedzi')) ?></option><option value="text"><?= e(t('admin.partials.campaign_surveys.odpowiedz_tekstowa')) ?></option></select></label>
        <label class="field"><span><?= e(t('editorial.editing.display_order')) ?></span><input type="number" name="sort_order" value="0"></label>
        <label class="field full"><span><?= e(t('admin.partials.campaign_surveys.opcje_odpowiedzi')) ?></span><textarea name="options" rows="4" placeholder="<?= e(t('admin.partials.campaign_surveys.kazda_opcja_w_osobnej_linii')) ?>"></textarea><small><?= e(t('admin.partials.campaign_surveys.dla_odpowiedzi_tekstowej_pozostaw_puste')) ?></small></label>
        <label class="field zs-checkbox-field"><input type="checkbox" name="is_required" value="1" checked><span><?= e(t('admin.partials.campaign_surveys.odpowiedz_wymagana')) ?></span></label>
        <div><button class="btn-red" type="submit"><?= e(t('admin.partials.campaign_surveys.dodaj_pytanie')) ?></button></div>
      </form>
      <div class="zs-question-list"><?php foreach($selected_questions as $question):?><article><div><strong><?= e((string)$question['question_text']) ?></strong><small><?= e($questionTypeLabels[(string)$question['question_type']]??t('admin.partials.campaign_surveys.odpowiedz')) ?><?= (int)$question['is_required']===1?' · '.e(t('admin.common.required')):'' ?></small></div><form method="post" action="/admin/surveys/questions/delete" onsubmit="return confirm(<?= e(json_encode(t('admin.surveys.confirm_delete_question'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) ?>)"><?= csrf_field() ?><input type="hidden" name="survey_id" value="<?= (int)$surveyEdit['id'] ?>"><input type="hidden" name="question_id" value="<?= (int)$question['id'] ?>"><button class="btn-line compact" type="submit"><?= e(t('author.article.remove_image')) ?></button></form></article><?php endforeach;?></div>
    </details>
  <?php endif;?>
</section>

<section class="admin-panel-block"><div class="admin-section-head"><div><p class="kicker"><?= e(t('admin.partials.campaign_surveys.ankiety_w_systemie')) ?></p><h2><?= e(t('admin.partials.campaign_surveys.wybierz_edytuj_lub_sprawdz_wyniki')) ?></h2></div><span><?= e(str_replace('{count}', (string)count($surveys), t('admin.common.items_count'))) ?></span></div>
<?php if($surveys===[]):?><div class="empty-state"><p><?= e(t('admin.partials.campaign_surveys.nie_ma_jeszcze_ankiet')) ?></p></div><?php else:?><div class="admin-table-wrap"><table class="zs-admin-table"><thead><tr><th><?= e(t('campaign.type.survey')) ?></th><th><?= e(t('admin.campaigns.stan')) ?></th><th><?= e(t('survey.answers')) ?></th><th><?= e(t('admin.campaigns.kampania')) ?></th><th><?= e(t('admin.campaign_report.dziaanie')) ?></th></tr></thead><tbody><?php foreach($surveys as $survey):?><tr><td><strong><?= e((string)$survey['title']) ?></strong><small><?= e((string)($survey['client_name']??t('admin.partials.campaign_surveys.editorial_client'))) ?></small></td><td><?= e($surveyStatuses[(string)$survey['status']]??t('admin.partials.campaign_surveys.unknown_status')) ?></td><td><?= (int)($survey['responses_count']??0) ?><?= !empty($survey['max_responses'])?' / '.(int)$survey['max_responses']:'' ?></td><td><?php if(!empty($survey['campaign_id'])):?><a class="text-link" href="/admin/campaigns?tab=survey&id=<?= (int)$survey['campaign_id'] ?>"><?= e((string)$survey['campaign_name']) ?></a><small><?= e($surveyStatuses[(string)$survey['campaign_status']]??t('admin.partials.campaign_surveys.status_saved')) ?></small><?php else:?><span class="status-pill is-muted"><?= e(t('admin.partials.campaign_surveys.jeszcze_nieprzypieta')) ?></span><?php endif;?></td><td><a class="text-link" href="/admin/campaigns?tab=survey&survey_id=<?= (int)$survey['id'] ?>#ankiety"><?= e(t('author.dashboard.edit')) ?></a> · <a class="text-link" href="/admin/surveys/report?id=<?= (int)$survey['id'] ?>"><?= e(t('admin.campaigns.raport')) ?></a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
</section>
